let nations = {
	"aefoss": {
		"culture": "eolsung",
		"description": "Nestled between the high peaks of Grandmother and Grandfather Mountain, Aefoss is a high land of bitter winter winds and summer snow, but its people are hearty and strong. Yet on the frozen peaks, dark voices sometimes whisper.",
		"traits": ["Defensive", "Disciplined"],
		"score": ["prosperity", "culture"],
		"religion": "Northern (Alyrja)",
		"title": "Jarl",
		"bonus": "prosperity",
	},
	"balyucesu": {
		"culture": "anpilayn",
		"description": "The history of the people of Balyucesu is one of loss and oppression. Their Kings of the past held honor above reason and sailed away to answer the calls of their allies, leaving their own people with little defenses. When Balyucesu's allies turned on her and divided the kingdom up between themselves and the lord of Jaraslatr, the inhabitants of Balyucesu settled in for a long and slow resistance. The fires of rebellion now burn hotly in Balyucesu, and its people stand ready to reassert their right to self-rule.",
		"traits": ["Rebellious", "Patriotic"],
		"score": ["prosperity", "security"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "Lord",
		"bonus": "armies",
	},
	"celyn": {
		"culture": "anpilayn",
		"description": "Many nations have risen over the course of history, but Celyn was the first. Its venerable forests have inspired poet and prophet alike, and it was here that Iruhan lived most of his life and gave most of his teachings. In all walks of life, the people of Celyn try to uphold his teachings by bettering themselves and the world.",
		"traits": ["Evangelical", "Holy"],
		"score": ["prosperity", "religion"],
		"religion": "Iruhan (Chalice of Compassion)",
		"title": "King",
		"bonus": "prosperity",
	},
	"doomstoll": {
		"culture": "eolsung",
		"description": "At times bowed but never broken, Doomstoll's people have prospered under the greatest of leaders, and suffered under the worst of tyrants. Located centrally between all Eolsung nations and sharing many borders, Doomstoll is the center of Eolsung culture.",
		"traits": ["Patriotic", "Disciplined"],
		"score": ["prosperity", "culture", "glory"],
		"religion": "Northern (Rjinku)",
		"title": "Queen",
		"bonus": "navies",
	},
	"ejymsyn": {
		"culture": "tavian",
		"description": "Ejymsyn is a cultural crossroads. Though ethnically Tavian, its people largely accept and worship Iruhan, the Anpilayn God. Past generations of Ejymsyn have integrated members of all cultures, but as the famine worsens, Ejymsyn's ruler must face a difficult choice of which nations they should side with.",
		"traits": ["Mercantile", "Disciplined"],
		"score": ["prosperity"],
		"religion": "Iruhan (Tapestry of People)",
		"title": "King",
		"bonus": "prosperity",
		"legalIdeologiesOverride": ["Iruhan (Chalice of Compassion)", "Iruhan (Sword of Truth)", "Iruhan (Tapestry of People)", "Iruhan (Vessel of Faith)"],
	},
	"fiskrbaer": {
		"culture": "eolsung",
		"description": "Steeped in magical traditions, Fiskrbaer has historically been an aloof power, interefering in worldy affairs only as suits it and its mysterious agenda. However, as the famine worsens, Fiskrbaer cannot afford to ignore the world much longer.",
		"traits": ["Mystical", "Industrial"],
		"score": ["prosperity", "happiness"],
		"religion": "Northern (Lyskr)",
		"title": "Chieftess",
		"bonus": "prosperity",
	},
	"gangrjata": {
		"culture": "eolsung",
		"description": "From the bustling dock-side fish-markets to the high golden mines, Gangrjata is a nation of diverse colors, sounds, and smells. Though peaceful for most of its history, its armies are also known for honorable conduct in warfare, and Gangrjata has historically held close alliances with its neighbors and been a stabilizing force in the northwest. However, this history is built on peace and plenty, and as the famine intensifies, the leader of this ancient land must look to new strategies to acquire the food necessary to feed their people - and protect the food they already have.",
		"traits": ["Disciplined", "Heroic"],
		"score": ["prosperity", "security", "glory"],
		"religion": "Northern (Alyrja)",
		"title": "Jarl",
		"bonus": "food",
	},
	"hosshofn": {
		"culture": "eolsung",
		"description": "Ancient darkness lives in the deep places under Hosshofn, and sometimes creeps forth to the surface world in defiance of the sun. The people of this land live in fear and in symbiosis with that alien power, blending their worship of the Eolsung gods with their knowledge that there are forces older and perhaps more powerful than their dieties.",
		"traits": ["Imperialistic", "Mercantile"],
		"score": ["prosperity", "glory"],
		"religion": "Northern (Rjinku)",
		"title": "Jarl",
		"bonus": "navies",
	},
	"isla": {
		"culture": "tyrgaetan",
		"description": "The youngest nation of the world, Isla is a large landmass that was forcibly split from the continent by the horrific consequences of overuse of magic. Its storm-wracked shores and sheltered interior have protected it from aggression in the generation since its sundering, but its people have not been complacent or idle, and now stand ready to rejoin the world and force their will upon it.",
		"traits": ["Seafaring", "War-like"],
		"score": ["prosperity", "territory"],
		"religion": "Northern (Syrjen)",
		"title": "Chieftain",
		"bonus": "navies",
	},
	"jaraslatr": {
		"culture": "eolsung",
		"description": "Many nations know of war - Jaraslatr knows only of victory. Historically ruled by aggressive and successful jarls, Jaraslatr has made its name fearful even in the farthest reaches of the world. But the fortunes of nations can turn on a whim of fate - as the famine worsens, will her proud and unfailing people finally know the sting of defeat?",
		"traits": ["Heroic", "War-like"],
		"score": ["prosperity", "glory", "territory"],
		"religion": "Northern (Rjinku)",
		"title": "Jarl",
		"bonus": "navies",
	},
	"kyaradis": {
		"culture": "hansa",
		"description": "Kyaradis has been the source of most technological improvements to sea vessels, and the ingenuity of her shipwrights is matched only by the skill of her sailors. The constant storms of the western seas bother her people little as they pursue wealth and prosperity.",
		"traits": ["Ship-Building", "Seafaring"],
		"score": ["prosperity", "riches", "happiness"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "King",
		"bonus": "navies",
	},
	"landhylli": {
		"culture": "eolsung",
		"description": "The island nation of Landhylli has bent knee to many rulers over the generations, both northern and southern. But the time of kings and queens is ending, and a fierce democratic ideal burns in Landhyllian hearts. Rise up, and reject the corrupt governments of the past! Yours is a nation of the people, by the people, and for the people, and it is up to you to make certain that democracy does not perish from this earth.",
		"traits": ["Republican", "Rebellious"],
		"score": ["prosperity", "happiness", "riches"],
		"religion": "Northern (Alyrja)",
		"title": "Prime Minister",
		"bonus": "navies",
	},
	"mabe": {
		"culture": "hansa",
		"description": "The sailors of Mabe are matchless in their tenacity and appetite for conquest. A nation of ports, Mabe is well-equipped to form strong local alliances and expand overseas - but its ruler must be careful not to awaken the ancient alliances that would oppose it.",
		"traits": ["Imperialistic", "War-like"],
		"score": ["prosperity", "security", "territory"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "King",
		"bonus": "armies",
	},
	"nysiunarri": {
		"culture": "anpilayn",
		"description": "No nation has been as badly scarred by the horrors of war as Nysiunarri. Invaded generations ago by their Eolsung neighbors, the soldiers of Nysiunarri and her allies rallied in time to save their sovereignty, but returned to desolate lands drained of population and resources. Nysiunarri is weak - can it find strength anew?",
		"traits": ["Defensive", "Stoic"],
		"score": ["prosperity", "culture"],
		"religion": "Iruhan (Tapestry of People)",
		"title": "King",
		"bonus": "gold",
	},
	"orkatopt": {
		"culture": "eolsung",
		"description": "Shrouded in mystery, other lands know little of Orkatopt save for the fear that its sails strike into their hearts. These raiders historically care little for the concerns of other lands, their remote lords simply demanding tribute from the weak and evading the strong. In these changing times, can Orkatopt remain as it has, or must it adapt to survive?",
		"traits": ["Ship-Building", "Imperialistic"],
		"score": ["prosperity", "riches", "glory"],
		"religion": "Northern (Syrjen)",
		"title": "Jarl",
		"bonus": "navies",
	},
	"pernepulse": {
		"culture": "anpilayn",
		"description": "The clever and honorable people of Pernepulse are known the world over for their beautiful cities and cathedrals, for their rich adornments and unwavering belief in the goodness of Iruhan. Yet the famine has power to shake even the strongest of faiths, and Pernepulse has not been spared. How will her people - and their leader - react?",
		"traits": ["Industrial", "Evangelical"],
		"score": ["prosperity", "ideology"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "King",
		"bonus": "armies",
	},
	"quencalia": {
		"culture": "tavian",
		"description": "Quencalia is a loose confederation of southern states and trade unions, bound together in the face of repeated aggression from its Anpilayn neighbors. Quencalians believe in hoping for the best while preparing for the worst, and are capable of leveraging their knack for mutually beneficial trade deals while looking to secure themselves against aggressive neighbors.",
		"traits": ["Mercantile", "Defensive"],
		"score": ["prosperity", "happiness", "riches", "security"],
		"religion": "Tavian (River of Kuun)",
		"title": "Warlord",
		"bonus": "food",
	},
	"rettrsvelt": {
		"culture": "tyrgaetan",
		"description": "The numerous nomadic tribes that live among the fierce and inhospitible lands of the Atjanfjall are the northern-most dwelling peoples in the world. United for common security against their hostile and aggresive Eolsung neighbors, the Rettrsvelt need a clever and strong leader to fend off both hungry enemies and hunger itself.",
		"traits": ["Stoic", "Mystical"],
		"score": ["prosperity"],
		"religion": "Northern (Alyrja)",
		"title": "Chieftain",
		"bonus": "armies",
	},
	"slail": {
		"culture": "anpilayn",
		"description": "The warm sunlight and timbered mountains of Slail may lull the visitor into relaxed bliss, but her people are anything but lazy. Industrious and shrewd, the inhabitants of Slail seek ever growing greatness, and have the natural resources to achieve it.",
		"traits": ["Industrial", "Ship-Building"],
		"score": ["prosperity", "happiness"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "King",
		"bonus": "gold",
	},
	"tavia": {
		"culture": "tavian",
		"description": "Long considered barbaric and godless outsiders by the rest of the civilized world, the many city-states of the Tavian deserts have at last been united under Tavia's current leader. Is this powerful figure now contented? Or will they set their sights on the rest of the world?",
		"traits": ["War-like", "Mystical"],
		"score": ["prosperity", "culture", "territory"],
		"religion": "Tavian (Flame of Kith)",
		"title": "Warlady",
		"bonus": "armies",
	},
	"upiceil": {
		"culture": "anpilayn",
		"description": "The holiest of holy nations, Upiceil's borders encompass Sancta Civitate, the place of the death and resurrection of Iruhan, and the seat of the powerful and hierarchical Church of Iruhan. The influence of the Church can be felt everywhere in Upiceil, and the special access Upiceil's leader has to the ears of the Church's elite can be felt the world over.",
		"traits": ["Holy", "Defensive"],
		"score": ["prosperity", "culture", "religion"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "King",
		"bonus": "navies",
	},
	"varthavaettr": {
		"culture": "tyrgaetan",
		"description": "Though all Tyrgaetan make their homes among inhospitable lands, the Varthavaettr are something else entirely. Legends say this tribe was born from the volcanic fires of Grind itself, and expanded over the lava-covered land, eating nothing but rock and drinking nothing but cups of smoke. Though other kingdoms dismiss such rumors as mere exaggerations, none that have met them in trade or in battle can deny that there is something different about these people...",
		"traits": ["Disciplined", "War-like"],
		"score": ["prosperity", "territory", "culture"],
		"religion": "Northern (Rjinku)",
		"title": "Warlord",
		"bonus": "navies",
	},
	"walymyn": {
		"culture": "anpilayn",
		"description": "Walymyn has been kingless for generations, as its occupiers try to bury and forget its passionate past. But secrets lie in shallow graves, and ancient bloodlines conspire to return Walymyn to her former glory. The people clamor for a return to the days of old, when their armies swept aside heathen and heretic alike, and razed their evil monuments to the foundation stones. Yet a wise ruler knows that aggression must be measured and supported, or Walymyn will suffer again its previous fate. It is doubtless that the might of Walymyn will again be felt - but what form will it take?",
		"traits": ["Patriotic", "Rebellious"],
		"score": ["prosperity", "territory", "glory", "religion", "ideology"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "King",
		"bonus": "armies",
	},
	"xilyn": {
		"culture": "anpilayn",
		"description": "Xilyn has grown from a collection of monestaries and holy orders into a unified kingdom in its own right. The lives of its people are centered around their religious devotion and they often view themselves as the true guardians of the faith - an attitude ideologically opposed nations do not appreciate.",
		"traits": ["Holy", "Mystical"],
		"score": ["prosperity", "ideology", "happiness", "culture"],
		"religion": "Iruhan (Chalice of Compassion)",
		"title": "Queen",
		"bonus": "armies",
	},
	"yrslekye": {
		"culture": "anpilayn",
		"description": "Amidst the most travelled seas of the world sit the isles of Yrslekye. Fiercely independent and skilled at balancing investment in defense and trade, the lords and ladies of Yrslekye are cosmopolitan polyglots who deal with north and south alike. But as starvation sets in and global conflict escalates, straddling the fences may no longer be feasible...",
		"traits": ["Defensive", "Seafaring"],
		"score": ["prosperity", "riches", "ideology"],
		"religion": "Iruhan (Tapestry of People)",
		"title": "Lady",
		"bonus": "gold",
	},
	"zemsim": {
		"culture": "anpilayn",
		"description": "Deep in the south, Zemsim is a land of wild jungles, ancient mystics, and dangerous subterfuge. Topographically dominated by Sion, the holy mountain upon which Iruhan ascended into Godhood, Zemsim’s many rivers make it a prosperous place. The majority of its inhabitants were converted to the worship of Iruhan long ago, but in some places, deep in the jungle, the old ways still live, and the drums of doom beat...",
		"traits": ["Republican", "Mystical"],
		"score": ["prosperity", "security"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "Chieftess",
		"bonus": "navies",
	},
};
