let nations = {
	"aefoss": {
		"culture": "eolsung",
		"description": "Nestled between the high peaks of Grandmother and Grandfather Mountain, Aefoss is a high land of bitter winter winds and summer snow, but its people are hearty and strong. Yet on the frozen peaks, dark voices sometimes whisper.",
		"traits": ["Defensive", "Disciplined"],
		"score": ["prosperity", "culture"],
		"religion": "Northern (Alyrja)",
		"title": "Jarl",
		"bonus": "prosperity",
	},
	"doomstoll": {
		"culture": "eolsung",
		"description": "At times bowed but never broken, Doomstoll's people have prospered under the greatest of leaders, and suffered under the worst of tyrants. Located centrally between all Eolsung nations and sharing many borders, Doomstoll is the center of Eolsung culture.",
		"traits": ["Patriotic", "Disciplined"],
		"score": ["prosperity", "culture", "glory"],
		"religion": "Northern (Rjinku)",
		"title": "Queen",
		"bonus": "navies",
	},
	"balyucesu": {
		"culture": "anpilayn",
		"description": "The history of the people of Balyucesu is one of loss and oppression. Their Kings of the past held honor above reason and sailed away to answer the calls of their allies, leaving their own people with little defenses. When Balyucesu's allies turned on her and divided the kingdom up between themselves and the lord of Jaraslatr, the inhabitants of Balyucesu settled in for a long and slow resistance. The fires of rebellion now burn hotly in Balyucesu, and its people stand ready to reassert their right to self-rule.",
		"traits": ["Rebellious", "Patriotic"],
		"score": ["prosperity", "security"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "Lord",
		"bonus": "armies",
	},
	"ejymsyn": {
		"culture": "tavian",
		"description": "Ejymsyn is a cultural crossroads. Though ethnically Tavian, its people largely accept and worship Iruhan, the Anpilayn God. Past generations of Ejymsyn have integrated members of all cultures, but as the famine worsens, Ejymsyn's ruler must face a difficult choice of which nations they should side with.",
		"traits": ["Mercantile", "Disciplined"],
		"score": ["prosperity"],
		"religion": "Iruhan (Tapestry of People)",
		"title": "King",
		"bonus": "prosperity",
		"legalIdeologiesOverride": ["Iruhan (Chalice of Compassion)", "Iruhan (Sword of Truth)", "Iruhan (Tapestry of People)", "Iruhan (Vessel of Faith)"],
	},
	"fiskrbaer": {
		"culture": "eolsung",
		"description": "Steeped in magical traditions, Fiskrbaer has historically been an aloof power, interefering in worldy affairs only as suits it and its mysterious agenda. However, as the famine worsens, Fiskrbaer cannot afford to ignore the world much longer.",
		"traits": ["Mystical", "Industrial"],
		"score": ["prosperity", "happiness"],
		"religion": "Northern (Lyskr)",
		"title": "Chieftess",
		"bonus": "prosperity",
	},
	"celyn": {
		"culture": "anpilayn",
		"description": "Many nations have risen over the course of history, but Celyn was the first. Its venerable forests have inspired poet and prophet alike, and it was here that Iruhan lived most of his life and gave most of his teachings. In all walks of life, the people of Celyn try to uphold his teachings by bettering themselves and the world.",
		"traits": ["Evangelical", "Holy"],
		"score": ["prosperity", "religion"],
		"religion": "Iruhan (Chalice of Compassion)",
		"title": "King",
		"bonus": "prosperity",
	},
	"jaraslatr": {
		"culture": "eolsung",
		"description": "Many nations know of war - Jaraslatr knows only of victory. Historically ruled by aggressive and successful jarls, Jaraslatr has made its name fearful even in the farthest reaches of the world. But the fortunes of nations can turn on a whim of fate - as the famine worsens, will her proud and unfailing people finally know the sting of defeat?",
		"traits": ["Heroic", "War-like"],
		"score": ["prosperity", "glory", "territory"],
		"religion": "Northern (Rjinku)",
		"title": "Jarl",
		"bonus": "navies",
	},
	"hosshofn": {
		"culture": "eolsung",
		"description": "Ancient darkness lives in the deep places under Hosshofn, and sometimes creeps forth to the surface world in defiance of the sun. The people of this land live in fear and in symbiosis with that alien power, blending their worship of the Eolsung gods with their knowledge that there are forces older and perhaps more powerful than their dieties.",
		"traits": ["Bloodthirsty", "Mercantile"],
		"score": ["prosperity", "glory"],
		"religion": "Northern (Rjinku)",
		"title": "Jarl",
		"bonus": "navies",
	},
	"isla": {
		"culture": "tyrgaetan",
		"description": "The youngest nation of the world, Isla is a large landmass that was forcibly split from the continent by the horrific consequences of overuse of magic. Its storm-wracked shores and sheltered interior have protected it from aggression in the generation since its sundering, but its people have not been complacent or idle, and now stand ready to rejoin the world and force their will upon it.",
		"traits": ["Seafaring", "War-like"],
		"score": ["prosperity", "territory"],
		"religion": "Northern (Syrjen)",
		"title": "Chieftain",
		"bonus": "navies",
	},
	"mabe": {
		"culture": "hansa",
		"description": "The sailors of Mabe are matchless in their tenacity and appetite for supremacy. A nation of ports, Mabe is discontiguous, holding multiple overseas colonies - and perhaps looking to establish more.",
		"traits": ["Imperialistic", "War-like"],
		"score": ["prosperity", "security", "territory"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "King",
		"bonus": "armies",
	},
	"kyaradis": {
		"culture": "hansa",
		"description": "Kyaradis has been the source of most technological improvements to sea vessels, and the ingenuity of her shipwrights is matched only by the skill of her sailors. The constant storms of the western seas bother her people little as they pursue wealth and prosperity.",
		"traits": ["Coast-Dwelling", "Seafaring"],
		"score": ["prosperity", "riches", "happiness"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "King",
		"bonus": "navies",
	},
	"nysiunarri": {
		"culture": "anpilayn",
		"description": "No nation has been as badly scarred by the horrors of war as Nysiunarri. Invaded generations ago by their Eolsung neighbors, the soldiers of Nysiunarri and her allies rallied in time to save their sovereignty, but returned to desolate lands drained of population and resources. Nysiunarri is weak - can it find strength anew?",
		"traits": ["Ruined", "Stoic"],
		"score": ["prosperity", "culture"],
		"religion": "Iruhan (Tapestry of People)",
		"title": "King",
		"bonus": "gold",
	},
	"pernepulse": {
		"culture": "anpilayn",
		"description": "The clever and honorable people of Pernepulse are known the world over for their beautiful cities and cathedrals, for their rich adornments and unwavering belief in the goodness of Iruhan. Yet the famine has power to shake even the strongest of faiths, and Pernepulse has not been spared. How will her people - and their leader - react?",
		"traits": ["Industrial", "Evangelical"],
		"score": ["prosperity", "ideology"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "King",
		"bonus": "armies",
	},
	"slail": {
		"culture": "anpilayn",
		"description": "The warm sunlight and timbered mountains of Slail may lull the visitor into relaxed bliss, but her people are anything but lazy. Industrious and shrewd, the inhabitants of Slail seek ever growing greatness, and have the natural resources to achieve it.",
		"traits": ["Industrial", "Ship-Building"],
		"score": ["prosperity", "happiness"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "King",
		"bonus": "gold",
	},
	"tavia": {
		"culture": "tavian",
		"description": "Long considered barbaric and godless outsiders by the rest of the civilized world, the many city-states of the Tavian deserts have at last been united under Tavia's current leader. Is this powerful figure now contented? Or will they set their sights on the rest of the world?",
		"traits": ["War-like", "Mystical"],
		"score": ["prosperity", "culture", "territory"],
		"religion": "Tavian (Flame of Kith)",
		"title": "Warlady",
		"bonus": "armies",
	},
	"upiceil": {
		"culture": "anpilayn",
		"description": "The holiest of holy nations, Upiceil's borders encompass Sancta Civitate, the place of the death and resurrection of Iruhan, and the seat of the powerful and hierarchical Church of Iruhan. The influence of the Church can be felt everywhere in Upiceil, and the special access Upiceil's leader has to the ears of the Church's elite can be felt the world over.",
		"traits": ["Holy", "Defensive"],
		"score": ["prosperity", "culture", "religion"],
		"religion": "Iruhan (Sword of Truth)",
		"title": "King",
		"bonus": "navies",
	},
	"rettrsvelt": {
		"culture": "tyrgaetan",
		"description": "The numerous nomadic tribes that live among the fierce and inhospitible lands of the Atjanfjall are the northern-most dwelling peoples in the world. United for common security against their hostile and aggresive Eolsung neighbors, the Rettrsvelt need a clever and strong leader to fend off both hungry enemies and hunger itself.",
		"traits": ["Nomadic", "Mystical"],
		"score": ["prosperity"],
		"religion": "Northern (Alyrja)",
		"title": "Chieftain",
		"bonus": "armies",
	},
	"zemsim": {
		"culture": "anpilayn",
		"description": "Deep in the south, Zemsim is a land of wild jungles, ancient mystics, and dangerous subterfuge. Topographically dominated by Sion, the holy mountain upon which Iruhan ascended into Godhood, Zemsim’s many rivers make it a prosperous place. The majority of its inhabitants were converted to the worship of Iruhan long ago, but in some places, deep in the jungle, the old ways still live, and the drums of doom beat...",
		"traits": ["Bloodthirsty", "Mystical"],
		"score": ["prosperity", "security"],
		"religion": "Iruhan (Vessel of Faith)",
		"title": "Chieftess",
		"bonus": "navies",
	},
};
