package com.empire;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Arrays;

class WorldConstantData {
	static final List<Double> harvests = Arrays.asList(new Double[]{8.5, 14.0, 19.5, 14.0});
	static final HashMap<String, Kingdom> kingdoms = new HashMap<>();
	static final ArrayList<Region> regions = new ArrayList<>();
	static final ArrayList<Border> borders = new ArrayList<>();

	static class Kingdom {
		public final String colorBg;
		public final String colorFg;
		public final String culture;
		public final int[] coreRegions;

		public Kingdom(String colorFg, String colorBg, String culture, int... coreRegions) {
			this.colorBg = colorBg;
			this.colorFg = colorFg;
			this.culture = culture;
			this.coreRegions = coreRegions;
		}
	}

	static class Region {
		public final String name;
		public final boolean land;
		public final String climate;

		public Region(String name, boolean land, String climate) {
			this.name = name;
			this.land = land;
			this.climate = climate;
		}
	}

	static class Border {
		public final int a;
		public final int b;
		public final int size;

		public Border(int a, int b, int size) {
			this.a = a;
			this.b = b;
			this.size = size;
		}
	}

	static enum Gender {
		MAN,
		WOMAN
	}

	static final HashMap<String, List<String>> names = new HashMap<>();

	static String getRandomName(String culture, Gender gender) {
		String g = gender == Gender.MAN ? "_m" : "_f";
		switch (culture) {
			case "eolsung":
				return pick(names.get("eolsung" + g)) + " " + (Math.random() < 0.4 ? pick(names.get("eolsung_m")) : pick(names.get("eolsung_f"))) + (gender == Gender.MAN ? "son" : "dottr");
			case "tyrgaetan":
				return pick(names.get("eolsung" + g)) + " " + pick(Arrays.asList(new String[]{"Alyrja", "Dagmyns", "Audityrs", "Thyrru", "Rjinku", "Syrjen", "Herja", "Lyskrs"})) + (Math.random() < 0.5 ? "ki" : "kun");
			case "tavian":
				return pick(names.get("tavian" + g));
			case "hansa":
				return pick(names.get("hansa" + g)) + " of " + pick(Arrays.asList(new String[]{"Windswine", "Sprayskimmer", "Farsight", "Cutlass", "Whitesail", "Elegant", "Prancer", "Dancer", "Vixen", "Comet", "Stargazer", "Starchaser", "Sunblinder", "Sunchaser", "Defiance", "Ridicule", "Interpid", "Seaswallow", "Hawkclaw", "Deathbringer", "Interceptor", "Wildsail", "Breezecoaster", "Shoalhugger", "Truthsayer", "Wavereaver", "Wavecutter", "Proudprow", "Proudsail", "Dauntless", "Milkysea", "Wakerunner", "Wakewing", "Wavetreader", "Forgotten", "Ancient", "Guardian", "Lostrudder", "Greensails", "Horizon", "Suntreader", "Moonglider", "Moonwalker", "Skyrunner", "Solitary", "Tidehunter", "Eversail", "Tiderocker", "Downwind", "Whirlwind", "Zephyr", "Cloudchaser"}));
			case "anpilayn":
				return pick(names.get("anpilayn1" + g)) + " " + pick(names.get("anpilayn2")) + " " + pick(names.get("anpilayn3" + g));
		}
		throw new RuntimeException("Unrecognized culture: " + culture);
	}

	private static <T> T pick(List<T> a) {
		return a.get((int)(Math.random() * a.size()));
	}

	static {
		kingdoms.put("Aefoss", new Kingdom("#ffffff", "#288ce5", "eolsung", 36, 37, 38, 43, 48, 50));
		kingdoms.put("Doomstoll", new Kingdom("#000000", "#feb300", "eolsung", 16, 22, 25, 31, 40, 42));
		kingdoms.put("Dumm", new Kingdom("#000000", "#e00059", "anpilayn", 41, 46, 47, 51, 54, 57));
		kingdoms.put("Ejymsyn", new Kingdom("#ffffff", "#644c66", "tavian", 76, 81, 83, 85, 92, 98));
		kingdoms.put("Fiskrbaer", new Kingdom("#ffffff", "#008c59", "eolsung", 12, 18, 23, 28, 32, 35));
		kingdoms.put("Fulyn", new Kingdom("#ffffff", "#003e00", "anpilayn", 60, 63, 65, 70, 71, 72));
		kingdoms.put("Holmslatr", new Kingdom("#000000", "#543eff", "eolsung", 24, 29, 33, 39, 44, 49));
		kingdoms.put("Hosshofn", new Kingdom("#ffffff", "#006672", "eolsung", 17, 20, 21, 26, 27, 34));
		kingdoms.put("Isla", new Kingdom("#ffffff", "#007f7f", "tyrgaetan", 8, 9, 10, 15, 19, 30));
		kingdoms.put("Mabe", new Kingdom("#000000", "#fcffbf", "hansa", 78, 84, 95, 104, 105, 111));
		kingdoms.put("Miycc", new Kingdom("#000000", "#d04c00", "hansa", 67, 77, 89, 101, 106, 117));
		kingdoms.put("Muoem", new Kingdom("#000000", "#00d800", "anpilayn", 52, 55, 58, 61, 64, 68));
		kingdoms.put("Siylmae", new Kingdom("#ffffff", "#000059", "anpilayn", 66, 69, 73, 75, 80, 86));
		kingdoms.put("Slail", new Kingdom("#000000", "#bc7fcc", "anpilayn", 110, 112, 113, 119, 120, 121));
		kingdoms.put("Tavia", new Kingdom("#000000", "#9a8c72", "tavian", 108, 109, 114, 115, 116, 118));
		kingdoms.put("Telmymsyn", new Kingdom("#ffffff", "#6b0000", "anpilayn", 87, 94, 96, 99, 100, 107));
		kingdoms.put("Tribes", new Kingdom("#000000", "#d9d9e5", "tyrgaetan", 0, 1, 2, 3, 4, 5, 6, 13, 14));
		kingdoms.put("Zemsim", new Kingdom("#ffffff", "#684c00", "anpilayn", 79, 82, 88, 90, 93, 97));
		regions.add(new Region("Crumble", true, "treacherous"));
		regions.add(new Region("Grind", true, "treacherous"));
		regions.add(new Region("Dread", true, "treacherous"));
		regions.add(new Region("Rust", true, "treacherous"));
		regions.add(new Region("Wear", true, "treacherous"));
		regions.add(new Region("Bend", true, "seasonal"));
		regions.add(new Region("Rot", true, "seasonal"));
		regions.add(new Region("Godslake", false, "green"));
		regions.add(new Region("Snowhelm", true, "treacherous"));
		regions.add(new Region("Hope's Landing", true, "seasonal"));
		regions.add(new Region("Icehaven", true, "seasonal"));
		regions.add(new Region("The Frozen Sea", false, "green"));
		regions.add(new Region("The Skull", true, "seasonal"));
		regions.add(new Region("Scour", true, "treacherous"));
		regions.add(new Region("Breach", true, "seasonal"));
		regions.add(new Region("Iceshore Pass", true, "seasonal"));
		regions.add(new Region("Silverguard", true, "seasonal"));
		regions.add(new Region("Feigt By", true, "seasonal"));
		regions.add(new Region("Startree", true, "seasonal"));
		regions.add(new Region("Winterwood Crest", true, "green"));
		regions.add(new Region("Søppelhavnen", true, "seasonal"));
		regions.add(new Region("Tisse Bøtte", true, "seasonal"));
		regions.add(new Region("Ravenhall", true, "seasonal"));
		regions.add(new Region("Magdalena's Well", true, "seasonal"));
		regions.add(new Region("Saltreach", true, "seasonal"));
		regions.add(new Region("Freehold", true, "seasonal"));
		regions.add(new Region("Lukt Avføring", true, "treacherous"));
		regions.add(new Region("Strålende Kloakk", true, "seasonal"));
		regions.add(new Region("Ghostwood", true, "treacherous"));
		regions.add(new Region("Razorwind Hold", true, "seasonal"));
		regions.add(new Region("Winterwood Vale", true, "green"));
		regions.add(new Region("Runestone", true, "green"));
		regions.add(new Region("Windstar", true, "seasonal"));
		regions.add(new Region("Kindlewood", true, "seasonal"));
		regions.add(new Region("Motbydelig", true, "seasonal"));
		regions.add(new Region("Bloodswamp", true, "green"));
		regions.add(new Region("Timberhold", true, "seasonal"));
		regions.add(new Region("Darkmountain", true, "treacherous"));
		regions.add(new Region("Whitewater", true, "seasonal"));
		regions.add(new Region("Firehall", true, "green"));
		regions.add(new Region("Justice Point", true, "green"));
		regions.add(new Region("Sweetwater", true, "seasonal"));
		regions.add(new Region("Silverspire", true, "seasonal"));
		regions.add(new Region("Foreverfall", true, "seasonal"));
		regions.add(new Region("Blackford", true, "green"));
		regions.add(new Region("The Eolshav", false, "green"));
		regions.add(new Region("Seafire Hollow", true, "seasonal"));
		regions.add(new Region("Fort Ruin", true, "seasonal"));
		regions.add(new Region("Grandfather Mountain", true, "treacherous"));
		regions.add(new Region("Saltbreeze", true, "green"));
		regions.add(new Region("Grandmother Mountain", true, "treacherous"));
		regions.add(new Region("Skyrock", true, "green"));
		regions.add(new Region("Keep Northguard", true, "seasonal"));
		regions.add(new Region("Stormwater", false, "green"));
		regions.add(new Region("Five Gates", true, "green"));
		regions.add(new Region("Mountainshadow", true, "green"));
		regions.add(new Region("The Sunrise Sea", false, "green"));
		regions.add(new Region("Lone Point", true, "green"));
		regions.add(new Region("Vigilant Shore", true, "green"));
		regions.add(new Region("The North Sea", false, "green"));
		regions.add(new Region("Whiteshore", true, "green"));
		regions.add(new Region("Fort Steadfast", true, "green"));
		regions.add(new Region("The Infinite Waters", false, "green"));
		regions.add(new Region("Riversmouth", true, "green"));
		regions.add(new Region("The Midlands", true, "green"));
		regions.add(new Region("Rocky Neck", true, "green"));
		regions.add(new Region("Whitesand", true, "green"));
		regions.add(new Region("Aleharbor", true, "green"));
		regions.add(new Region("Blackrock Peak", true, "green"));
		regions.add(new Region("Tumblebeach", true, "green"));
		regions.add(new Region("Dockside", true, "green"));
		regions.add(new Region("Greywood", true, "seasonal"));
		regions.add(new Region("Merchants' Rest", true, "seasonal"));
		regions.add(new Region("Rocksand", true, "green"));
		regions.add(new Region("The Crossing", false, "green"));
		regions.add(new Region("Greenwood", true, "seasonal"));
		regions.add(new Region("Cascadia", true, "green"));
		regions.add(new Region("Port Crown", true, "green"));
		regions.add(new Region("Highcliff", true, "green"));
		regions.add(new Region("Moonshadow Forest", true, "seasonal"));
		regions.add(new Region("Goldwood", true, "green"));
		regions.add(new Region("Sacred Way", true, "green"));
		regions.add(new Region("Moonsand", true, "green"));
		regions.add(new Region("Sunlake", true, "green"));
		regions.add(new Region("Sailkeep", true, "green"));
		regions.add(new Region("Field of Fallen Heroes", true, "green"));
		regions.add(new Region("Greymount", true, "green"));
		regions.add(new Region("Scribe's Hollow", true, "green"));
		regions.add(new Region("Mount Sion", true, "treacherous"));
		regions.add(new Region("Golden Docks", true, "green"));
		regions.add(new Region("Nightwood", true, "green"));
		regions.add(new Region("Neckwater", false, "green"));
		regions.add(new Region("Nightsands", true, "green"));
		regions.add(new Region("The Coast of Stars", true, "green"));
		regions.add(new Region("Widefield", true, "green"));
		regions.add(new Region("Clothridge", true, "green"));
		regions.add(new Region("Sevencourt", true, "green"));
		regions.add(new Region("Orchid's Perch", true, "green"));
		regions.add(new Region("Stacked Stones", true, "green"));
		regions.add(new Region("Summersage", true, "green"));
		regions.add(new Region("Sancta Civitate", true, "green"));
		regions.add(new Region("Wayfield Delta", true, "green"));
		regions.add(new Region("The Gulf", false, "green"));
		regions.add(new Region("The Holy Waters", false, "green"));
		regions.add(new Region("Ashpeak Vale", true, "green"));
		regions.add(new Region("Silverdell", true, "green"));
		regions.add(new Region("Coinwell", true, "green"));
		regions.add(new Region("Greatriver", true, "green"));
		regions.add(new Region("Endless Beauty", true, "green"));
		regions.add(new Region("Ebon Sands", true, "treacherous"));
		regions.add(new Region("Clearwater", true, "green"));
		regions.add(new Region("Marbletop", true, "green"));
		regions.add(new Region("Falcon's Rest", true, "green"));
		regions.add(new Region("Fangriver", true, "green"));
		regions.add(new Region("Myriad Oases", true, "green"));
		regions.add(new Region("Many Roads", true, "green"));
		regions.add(new Region("Hundred Spires", true, "treacherous"));
		regions.add(new Region("Bleakridge", true, "green"));
		regions.add(new Region("Countless Histories", true, "treacherous"));
		regions.add(new Region("Crystal Bay", true, "green"));
		regions.add(new Region("Wolfden", true, "green"));
		regions.add(new Region("Deerwood", true, "green"));
		borders.add(new Border(0,3,2));
		borders.add(new Border(0,7,1));
		borders.add(new Border(0,7,1));
		borders.add(new Border(0,7,1));
		borders.add(new Border(1,4,3));
		borders.add(new Border(1,6,2));
		borders.add(new Border(1,3,3));
		borders.add(new Border(2,11,1));
		borders.add(new Border(2,5,2));
		borders.add(new Border(2,4,2));
		borders.add(new Border(11,8,1));
		borders.add(new Border(3,6,2));
		borders.add(new Border(3,14,2));
		borders.add(new Border(3,7,1));
		borders.add(new Border(4,5,2));
		borders.add(new Border(4,13,2));
		borders.add(new Border(4,6,2));
		borders.add(new Border(11,10,1));
		borders.add(new Border(11,8,1));
		borders.add(new Border(11,5,1));
		borders.add(new Border(11,8,1));
		borders.add(new Border(11,9,1));
		borders.add(new Border(7,12,1));
		borders.add(new Border(5,11,1));
		borders.add(new Border(5,17,1));
		borders.add(new Border(5,13,2));
		borders.add(new Border(6,13,2));
		borders.add(new Border(6,16,1));
		borders.add(new Border(6,14,2));
		borders.add(new Border(8,10,1));
		borders.add(new Border(8,15,3));
		borders.add(new Border(8,9,2));
		borders.add(new Border(11,10,1));
		borders.add(new Border(11,9,1));
		borders.add(new Border(11,59,1));
		borders.add(new Border(7,14,1));
		borders.add(new Border(7,12,1));
		borders.add(new Border(9,15,1));
		borders.add(new Border(9,59,1));
		borders.add(new Border(9,59,1));
		borders.add(new Border(10,11,1));
		borders.add(new Border(10,19,2));
		borders.add(new Border(10,15,3));
		borders.add(new Border(11,20,1));
		borders.add(new Border(11,17,1));
		borders.add(new Border(12,7,1));
		borders.add(new Border(12,7,1));
		borders.add(new Border(12,7,1));
		borders.add(new Border(7,18,1));
		borders.add(new Border(13,17,2));
		borders.add(new Border(13,21,1));
		borders.add(new Border(13,16,1));
		borders.add(new Border(14,16,2));
		borders.add(new Border(14,22,1));
		borders.add(new Border(14,7,1));
		borders.add(new Border(7,23,1));
		borders.add(new Border(7,18,1));
		borders.add(new Border(15,19,2));
		borders.add(new Border(15,59,1));
		borders.add(new Border(15,59,1));
		borders.add(new Border(16,21,1));
		borders.add(new Border(16,25,1));
		borders.add(new Border(16,22,2));
		borders.add(new Border(7,22,1));
		borders.add(new Border(59,24,1));
		borders.add(new Border(59,20,1));
		borders.add(new Border(11,59,1));
		borders.add(new Border(11,19,1));
		borders.add(new Border(17,20,1));
		borders.add(new Border(17,26,2));
		borders.add(new Border(17,21,2));
		borders.add(new Border(7,32,1));
		borders.add(new Border(7,23,1));
		borders.add(new Border(18,23,1));
		borders.add(new Border(18,28,2));
		borders.add(new Border(19,59,1));
		borders.add(new Border(19,30,1));
		borders.add(new Border(19,59,1));
		borders.add(new Border(20,24,1));
		borders.add(new Border(20,33,1));
		borders.add(new Border(20,26,2));
		borders.add(new Border(21,26,1));
		borders.add(new Border(21,27,1));
		borders.add(new Border(21,25,1));
		borders.add(new Border(22,25,2));
		borders.add(new Border(22,31,1));
		borders.add(new Border(22,7,1));
		borders.add(new Border(59,29,1));
		borders.add(new Border(59,24,1));
		borders.add(new Border(23,32,1));
		borders.add(new Border(23,36,1));
		borders.add(new Border(23,28,2));
		borders.add(new Border(24,29,1));
		borders.add(new Border(24,59,1));
		borders.add(new Border(24,33,1));
		borders.add(new Border(25,27,1));
		borders.add(new Border(25,45,1));
		borders.add(new Border(25,31,1));
		borders.add(new Border(7,31,1));
		borders.add(new Border(7,35,1));
		borders.add(new Border(7,32,1));
		borders.add(new Border(59,30,1));
		borders.add(new Border(26,33,2));
		borders.add(new Border(26,34,1));
		borders.add(new Border(26,27,1));
		borders.add(new Border(59,30,1));
		borders.add(new Border(59,29,1));
		borders.add(new Border(27,34,1));
		borders.add(new Border(27,45,1));
		borders.add(new Border(27,45,1));
		borders.add(new Border(28,36,2));
		borders.add(new Border(28,37,2));
		borders.add(new Border(29,59,1));
		borders.add(new Border(29,59,1));
		borders.add(new Border(29,59,1));
		borders.add(new Border(30,59,1));
		borders.add(new Border(30,59,1));
		borders.add(new Border(30,59,1));
		borders.add(new Border(31,45,1));
		borders.add(new Border(31,40,1));
		borders.add(new Border(31,35,1));
		borders.add(new Border(32,35,1));
		borders.add(new Border(32,38,1));
		borders.add(new Border(32,36,1));
		borders.add(new Border(33,59,1));
		borders.add(new Border(33,39,1));
		borders.add(new Border(33,34,2));
		borders.add(new Border(34,39,2));
		borders.add(new Border(34,45,1));
		borders.add(new Border(34,45,1));
		borders.add(new Border(59,41,1));
		borders.add(new Border(35,40,1));
		borders.add(new Border(35,42,1));
		borders.add(new Border(35,38,1));
		borders.add(new Border(45,40,1));
		borders.add(new Border(36,38,1));
		borders.add(new Border(36,43,1));
		borders.add(new Border(36,37,1));
		borders.add(new Border(59,44,1));
		borders.add(new Border(59,39,1));
		borders.add(new Border(59,46,1));
		borders.add(new Border(59,41,1));
		borders.add(new Border(59,41,1));
		borders.add(new Border(59,47,1));
		borders.add(new Border(59,44,1));
		borders.add(new Border(37,43,2));
		borders.add(new Border(37,48,1));
		borders.add(new Border(45,53,1));
		borders.add(new Border(38,42,1));
		borders.add(new Border(38,50,1));
		borders.add(new Border(38,43,1));
		borders.add(new Border(39,44,1));
		borders.add(new Border(39,49,1));
		borders.add(new Border(39,45,1));
		borders.add(new Border(40,45,1));
		borders.add(new Border(40,45,1));
		borders.add(new Border(40,42,1));
		borders.add(new Border(41,46,1));
		borders.add(new Border(41,51,2));
		borders.add(new Border(41,47,1));
		borders.add(new Border(42,45,1));
		borders.add(new Border(42,56,1));
		borders.add(new Border(42,50,1));
		borders.add(new Border(43,50,2));
		borders.add(new Border(43,52,1));
		borders.add(new Border(43,48,2));
		borders.add(new Border(45,49,1));
		borders.add(new Border(44,47,1));
		borders.add(new Border(44,53,1));
		borders.add(new Border(44,49,1));
		borders.add(new Border(59,46,1));
		borders.add(new Border(45,56,1));
		borders.add(new Border(46,59,1));
		borders.add(new Border(46,57,1));
		borders.add(new Border(46,51,2));
		borders.add(new Border(47,51,2));
		borders.add(new Border(47,54,2));
		borders.add(new Border(47,53,1));
		borders.add(new Border(48,52,3));
		borders.add(new Border(48,55,3));
		borders.add(new Border(49,53,1));
		borders.add(new Border(49,53,1));
		borders.add(new Border(49,53,1));
		borders.add(new Border(50,56,1));
		borders.add(new Border(50,56,1));
		borders.add(new Border(50,52,3));
		borders.add(new Border(51,57,1));
		borders.add(new Border(51,74,1));
		borders.add(new Border(51,54,1));
		borders.add(new Border(59,57,1));
		borders.add(new Border(53,54,1));
		borders.add(new Border(52,56,1));
		borders.add(new Border(52,58,1));
		borders.add(new Border(52,55,1));
		borders.add(new Border(56,58,1));
		borders.add(new Border(53,60,1));
		borders.add(new Border(53,56,1));
		borders.add(new Border(54,74,1));
		borders.add(new Border(54,74,1));
		borders.add(new Border(54,53,1));
		borders.add(new Border(55,58,1));
		borders.add(new Border(55,61,2));
		borders.add(new Border(57,59,1));
		borders.add(new Border(57,74,1));
		borders.add(new Border(57,74,1));
		borders.add(new Border(58,56,1));
		borders.add(new Border(58,64,1));
		borders.add(new Border(58,61,1));
		borders.add(new Border(56,60,1));
		borders.add(new Border(56,66,1));
		borders.add(new Border(53,63,1));
		borders.add(new Border(53,60,1));
		borders.add(new Border(59,62,1));
		borders.add(new Border(59,74,1));
		borders.add(new Border(53,74,1));
		borders.add(new Border(53,65,1));
		borders.add(new Border(56,66,1));
		borders.add(new Border(56,69,1));
		borders.add(new Border(56,64,1));
		borders.add(new Border(60,63,1));
		borders.add(new Border(60,71,1));
		borders.add(new Border(60,66,1));
		borders.add(new Border(61,64,2));
		borders.add(new Border(61,68,1));
		borders.add(new Border(74,62,1));
		borders.add(new Border(74,67,1));
		borders.add(new Border(53,65,1));
		borders.add(new Border(53,70,1));
		borders.add(new Border(53,63,1));
		borders.add(new Border(74,65,1));
		borders.add(new Border(62,67,1));
		borders.add(new Border(74,67,1));
		borders.add(new Border(56,69,1));
		borders.add(new Border(56,73,1));
		borders.add(new Border(63,70,1));
		borders.add(new Border(63,72,1));
		borders.add(new Border(63,71,1));
		borders.add(new Border(64,56,1));
		borders.add(new Border(64,76,1));
		borders.add(new Border(64,68,2));
		borders.add(new Border(65,74,1));
		borders.add(new Border(65,91,1));
		borders.add(new Border(65,70,1));
		borders.add(new Border(66,71,1));
		borders.add(new Border(66,75,1));
		borders.add(new Border(66,69,1));
		borders.add(new Border(67,62,1));
		borders.add(new Border(67,77,1));
		borders.add(new Border(67,74,1));
		borders.add(new Border(56,73,1));
		borders.add(new Border(56,81,1));
		borders.add(new Border(56,76,1));
		borders.add(new Border(68,76,2));
		borders.add(new Border(68,83,1));
		borders.add(new Border(69,75,1));
		borders.add(new Border(69,80,1));
		borders.add(new Border(69,73,1));
		borders.add(new Border(74,78,1));
		borders.add(new Border(74,91,1));
		borders.add(new Border(70,91,1));
		borders.add(new Border(70,82,1));
		borders.add(new Border(70,72,1));
		borders.add(new Border(71,72,1));
		borders.add(new Border(71,79,2));
		borders.add(new Border(71,75,2));
		borders.add(new Border(91,78,1));
		borders.add(new Border(91,82,1));
		borders.add(new Border(72,82,2));
		borders.add(new Border(72,88,3));
		borders.add(new Border(72,79,2));
		borders.add(new Border(73,80,1));
		borders.add(new Border(73,87,1));
		borders.add(new Border(73,81,1));
		borders.add(new Border(74,77,1));
		borders.add(new Border(74,84,1));
		borders.add(new Border(74,78,1));
		borders.add(new Border(62,77,1));
		borders.add(new Border(75,79,1));
		borders.add(new Border(75,86,1));
		borders.add(new Border(75,80,1));
		borders.add(new Border(76,81,1));
		borders.add(new Border(76,85,2));
		borders.add(new Border(76,83,2));
		borders.add(new Border(77,62,1));
		borders.add(new Border(77,89,1));
		borders.add(new Border(77,84,1));
		borders.add(new Border(78,84,1));
		borders.add(new Border(78,91,1));
		borders.add(new Border(78,91,1));
		borders.add(new Border(79,88,2));
		borders.add(new Border(79,90,1));
		borders.add(new Border(79,86,1));
		borders.add(new Border(80,86,1));
		borders.add(new Border(80,94,1));
		borders.add(new Border(80,87,1));
		borders.add(new Border(81,87,1));
		borders.add(new Border(81,103,1));
		borders.add(new Border(81,85,1));
		borders.add(new Border(82,91,1));
		borders.add(new Border(82,93,1));
		borders.add(new Border(82,88,2));
		borders.add(new Border(83,85,2));
		borders.add(new Border(83,92,2));
		borders.add(new Border(84,89,2));
		borders.add(new Border(84,95,1));
		borders.add(new Border(84,91,1));
		borders.add(new Border(91,93,1));
		borders.add(new Border(62,89,1));
		borders.add(new Border(85,103,1));
		borders.add(new Border(85,103,1));
		borders.add(new Border(85,92,1));
		borders.add(new Border(86,90,1));
		borders.add(new Border(86,96,1));
		borders.add(new Border(86,94,1));
		borders.add(new Border(87,94,1));
		borders.add(new Border(87,103,1));
		borders.add(new Border(87,103,1));
		borders.add(new Border(88,93,2));
		borders.add(new Border(88,97,2));
		borders.add(new Border(88,90,2));
		borders.add(new Border(89,62,1));
		borders.add(new Border(89,101,1));
		borders.add(new Border(89,95,2));
		borders.add(new Border(90,97,1));
		borders.add(new Border(90,102,1));
		borders.add(new Border(90,96,1));
		borders.add(new Border(103,100,1));
		borders.add(new Border(91,95,1));
		borders.add(new Border(92,103,1));
		borders.add(new Border(92,98,2));
		borders.add(new Border(93,91,1));
		borders.add(new Border(93,102,1));
		borders.add(new Border(93,97,1));
		borders.add(new Border(94,96,1));
		borders.add(new Border(94,99,1));
		borders.add(new Border(94,103,1));
		borders.add(new Border(95,101,2));
		borders.add(new Border(95,104,1));
		borders.add(new Border(95,91,1));
		borders.add(new Border(103,99,1));
		borders.add(new Border(103,100,1));
		borders.add(new Border(96,102,1));
		borders.add(new Border(96,102,1));
		borders.add(new Border(96,99,1));
		borders.add(new Border(97,102,1));
		borders.add(new Border(97,102,1));
		borders.add(new Border(97,102,1));
		borders.add(new Border(91,102,1));
		borders.add(new Border(103,100,1));
		borders.add(new Border(103,98,1));
		borders.add(new Border(62,101,1));
		borders.add(new Border(98,103,1));
		borders.add(new Border(98,108,2));
		borders.add(new Border(99,102,1));
		borders.add(new Border(99,107,1));
		borders.add(new Border(99,103,1));
		borders.add(new Border(91,104,1));
		borders.add(new Border(91,105,1));
		borders.add(new Border(100,103,1));
		borders.add(new Border(100,103,1));
		borders.add(new Border(100,103,1));
		borders.add(new Border(101,62,1));
		borders.add(new Border(101,106,1));
		borders.add(new Border(101,104,2));
		borders.add(new Border(103,107,1));
		borders.add(new Border(103,114,1));
		borders.add(new Border(102,105,1));
		borders.add(new Border(102,113,1));
		borders.add(new Border(102,110,1));
		borders.add(new Border(103,109,1));
		borders.add(new Border(103,108,1));
		borders.add(new Border(62,106,1));
		borders.add(new Border(102,112,1));
		borders.add(new Border(102,107,1));
		borders.add(new Border(104,106,2));
		borders.add(new Border(104,111,2));
		borders.add(new Border(104,105,1));
		borders.add(new Border(105,111,1));
		borders.add(new Border(105,121,1));
		borders.add(new Border(105,113,1));
		borders.add(new Border(102,113,1));
		borders.add(new Border(102,120,1));
		borders.add(new Border(102,110,1));
		borders.add(new Border(106,62,1));
		borders.add(new Border(106,117,1));
		borders.add(new Border(106,111,2));
		borders.add(new Border(103,114,1));
		borders.add(new Border(103,116,1));
		borders.add(new Border(103,109,1));
		borders.add(new Border(107,112,1));
		borders.add(new Border(107,115,1));
		borders.add(new Border(107,114,1));
		borders.add(new Border(108,109,2));
		borders.add(new Border(108,118,2));
		borders.add(new Border(102,110,1));
		borders.add(new Border(102,119,1));
		borders.add(new Border(102,112,1));
		borders.add(new Border(109,116,2));
		borders.add(new Border(109,118,2));
		borders.add(new Border(62,117,1));
		borders.add(new Border(110,120,1));
		borders.add(new Border(110,119,1));
		borders.add(new Border(111,117,3));
		borders.add(new Border(111,121,1));
		borders.add(new Border(112,119,1));
		borders.add(new Border(112,115,1));
		borders.add(new Border(113,121,1));
		borders.add(new Border(113,120,1));
		borders.add(new Border(114,115,2));
		borders.add(new Border(114,116,2));

		// NAMES
		String anpilayn1f = "Abe,Abi,Acadier,Ace,Acedir,Acedire,Acedirr,Acedirre,Acedirri,Aceyle,Acurbi,Aduroe,Aiwe,Alac,Alame,Alim,Alimi,Alnamjelb,Alne,Alnharb,Alnimslyb,Alnjelb,Alnsleyb,Alnslyb,Alnycqe,Ame,Amje,Amji,Amjidulj,Amjidylj,Amjlab,Amqe,Anne,Annetyrese,Anqi,Ara,Aramte,Araqi,Arba,Arbaqu,Arbu,Arce,Arci,Arieme,Arqe,Arume,Arumqe,Ase,Aueme,Aumire,Aurembe,Awummi,Axabule,Axedirre,Ayari,Aycsame,Ayrae,Ayraeme,Aytymbe,Baeme,Baisrambi,Baumocae,Bealami,Beame,Bejmage,Bejnel,Belae,Belame,Bemaire,Beme,Benhmeas,Betaeme,Bialbli,Bialdhari,Bicabilae,Bicabilese,Bidule,Bieldhear,Bilware,Bilwer,Bilwre,Bimace,Binisle,Birae,Birne,Birphame,Biwam,Biwmis,Bonphme,Bonpme,Bualiemm,Buame,Bulac,Bulame,Bule,Bulqe,Bulshi,Bulushie,Bulussoe,Bumese,Bunamate,Byta,Cabumae,Cadier,Cadorre,Cadorri,Caijharb,Caijrambi,Caja,Cami,Camieb,Canume,Cari,Carqi,Carwae,Cashneash,Caudhem,Caufle,Caunhe,Cawi,Ceadh,Cebd,Cebdh,Cebhdh,Cecqae,Cecthe,Cedame,Cedami,Cedlame,Cela,Celaqe,Cele,Celeab,Celeh,Cembe,Cemble,Ceruni,Cerweslaz,Ceualci,Ceyri,Chewummi,Chiare,Chie,Chiweym,Chiwum,Cielreas,Cilephame,Cilime,Cimse,Cirne,Ciwilame,Codarre,Codarri,Corwae,Cpilemsae,Creami,Csifemae,Csifemai,Csiffa,Csiffai,Csiphemai,Csire,Cthurecsate,Cthvemharb,Cufae,Cufage,Cufai,Culame,Culthe,Cumae,Cumge,Cumgi,Cuphae,Cuphai,Currinmae,Curwiaje,Cvemharb,Cvemharbe,Cvemharbi,Cwimge,Cxarwae,Cxedame,Cxemble,Cxumge,Cyca,Cycemm,Cycemmi,Cyci,Dabbo,Dabirae,Dadaeme,Dadulqe,Daemqe,Daemte,Dealdli,Deldele,Deldir,Diadhamm,Dibirae,Didamm,Didhamm,Didhaumm,Diese,Diesi,Dieslaci,Dieslaz,Dilmebiss,Dilse,Dilshe,Dimajme,Dimibaqse,Dimibatse,Dissame,Diwam,Dlab,Dlabai,Dlabi,Dlabjis,Dlajab,Dlajase,Dlajasse,Dlajassi,Dlajh,Dlajhab,Dlembyce,Dlibe,Dlii,Dlujem,Dlumejh,Dlumeth,Dlymharb,Dlymharbi,Dreasham,Dremab,Dremqe,Dreshmeab,Dreshmes,Dujbeme,Dujrelqe,Duldere,Duluqe,Duxca,Eabiim,Eacram,Eacramj,Eacramm,Eaflat,Eajmiac,Eami,Eamjier,Earac,Eardhi,Eariim,Eashmi,Ebe,Ebir,Ebirame,Ebire,Ebireabe,Ebirhiab,Ebiri,Eblaeme,Eblaimm,Eccynpse,Echramj,Ecslab,Edajear,Edajir,Eflate,Efle,Eja,Ejeshi,Ejmage,Ejmic,Ejmici,Ejuse,Elaemi,Elem,Elemqe,Emame,Emaqe,Emaqu,Emase,Emble,Emblie,Embliie,Emcirne,Eme,Emecxsexae,Emenelae,Emesurae,Emge,Emirai,Emiss,Emjirame,Emjiraqe,Emjirate,Emjire,Emjoerqe,Emmaqe,Emme,Emmenelae,Emmerime,Emmi,Emmijlis,Emminelai,Emmirai,Emmiraic,Emmiraici,Emmiss,Emmissi,Emmycqe,Emqi,Emsgi,Emsumae,Emte,Enedarae,Enembe,Enerae,Enerai,Enese,Enirae,Enirai,Erabe,Eraci,Erame,Erax,Erdame,Erdami,Erdilsame,Erdilse,Erecslaume,Eremmeh,Erflibe,Eriabe,Erias,Erime,Eriz,Erizac,Erizae,Erizemblami,Erizemble,Eruacae,Euadham,Euadhi,Euadhiemm,Euafi,Ewe,Eyjycsami,Eyjycse,Eyjycsi,Eylie,Eylirae,Eylule,Fabirne,Fammjyere,Fammyere,Famrio,Famure,Faume,Faummjhyere,Faummyere,Faumure,Femma,Fiabhirn,Fibirne,Filbamembe,Firame,Firatae,Firataeme,Firatai,Firatasec,Firaxasec,Flaibe,Flaibi,Flaibilaqi,Flasxa,Flemqe,Flemta,Flemtacqe,Flemtacte,Flemxa,Flemxacqe,Flemxi,Fleyqi,Flige,Flyxcame,Fremm,Fremmem,Frewae,Frulame,Frule,Frulimsae,Frulimsame,Frulisse,Fulsymese,Gecnam,Gemame,Geme,Gexnam,Giccaqe,Giccate,Gimmafil,Gimmo,Girime,Gu,Gucifami,Guciphami,Guciphe,Guhemme,Gulbac,Gurem,Guremqe,Guxife,Gybas,Gybash,Gycsame,Gycsami,Gyra,Gyracqe,Gyrae,Gyraeme,Gyraemi,Gyraemme,Gysse,Gyssi,Harbe,Harbi,Harbijelb,Harbijelbi,Harsleyb,Harslyb,Harslybi,Hegma,Hegme,Hegmer,Hegmerqe,Hemje,Hemme,Hemmeh,Hemmi,Hemmi,Hemmiruli,Hiaba,Hiabe,Hiamlaqi,Hiaqi,Hiarvaj,Hibo,Hibvaj,Hilnami,Hilse,Hilshe,Himlaisse,Himlaissi,Himlaqi,Hirime,Hirimi,Hirje,Hirnami,Hirne,Hirre,Humulae,Humulame,Humule,Humulese,Hyrbe,Iadhram,Ialiemm,Ialiim,Ianhiel,Ianiel,Iarac,Iarach,Iariim,Iashmi,Ibame,Ibas,Ibash,Ibme,Icxsa,Icxsil,Idde,Iebem,Iebeuam,Iedhe,Iewem,Ilam,Ilaqe,Ilme,Ilmicsami,Ilnimslyb,Ilxca,Ilxcidis,Imaqu,Ime,Immac,Imoe,Inarae,Inarage,Inarai,Inici,Inil,Inne,Irace,Iracedise,Iracedish,Iraci,Irajae,Irame,Irase,Irce,Irci,Irflaibi,Irime,Iriumule,Iriumuli,Irne,Irqi,Irra,Irwe,Ishme,Ishmi,Isir,Isirqe,Isme,Itesilame,Iwaqi,Iwe,Iwiram,Iwirom,Iyfluxame,Iyjimae,Iyrerae,Jace,Jacire,Jasse,Jaxa,Jaxirre,Jeda,Jedlaire,Jedlairi,Jedlairre,Jewlare,Jilbe,Jilharb,Jilrambi,Jilsleyb,Jilslyb,Jiuljame,Jiuljise,Jlanhars,Jleammi,Jlemae,Jlemoe,Jlesae,Jlise,Jlisi,Jlisir,Jlisthim,Jouljoa,Jouljoaqi,Joumjoa,Jrulae,Judamis,Judmeas,Judmis,Julnfreash,Julnreash,Jyblym,Jymbe,Jymbyre,Kyalame,Kyamm,Lae,Laqi,Lase,Latelbe,Laume,Laumeth,Leanymbi,Leathier,Leffeire,Lehir,Lehire,Lejhmears,Lenume,Lepheire,Leryte,Leshmeas,Lethir,Liamharb,Liamharbi,Lidiqe,Lidiqqe,Liejem,Lijame,Lijami,Lijyre,Limese,Limesi,Liqe,Luac,Luacam,Lubate,Luce,Lucerae,Lucerai,Luchiim,Lucinelai,Lucvashe,Lumas,Luneme,Luno,Luvem,Luxca,Luxce,Luxe,Luxerae,Luxerage,Luzeme,Lysh,Lyzemble,Maenh,Mame,Maqure,Maquriss,Mature,Maturi,Maturise,Meamca,Mebami,Mebge,Mebixbe,Meltacce,Meltace,Meserae,Meserage,Meserai,Mesherai,Meunh,Micce,Miecce,Miece,Milshyc,Miri,Miwi,Mualam,Muina,Mule,Muleh,Muliim,Mulimi,Mure,Murreaj,Myere,Nae,Naheire,Nalaen,Nalgen,Nalire,Nalyme,Namme,Namubule,Narime,Nasxa,Natha,Natheire,Nealam,Neali,Nealieb,Nealimm,Neaqi,Nebeariam,Nebele,Neberame,Nege,Neiwi,Nejbe,Nejberime,Nejberimi,Nejburme,Nela,Nelacqe,Nelae,Nelae,Nelaeme,Nelaemme,Nelaemmi,Nelage,Nelai,Nelairi,Nelame,Nelaqe,Nelarime,Nelase,Nelate,Nele,Neliaqi,Neljas,Neljase,Neljelase,Neljelise,Neljelishe,Neljelishi,Neljelisi,Neljlas,Nelrac,Nelraic,Nelrim,Nelrimi,Nelsame,Nelse,Nelshe,Nelsycqe,Neltire,Neltirre,Nemy,Nemyire,Nerreabh,Nesarb,Nesharbi,Neslume,Newi,Newuylmiim,Neylami,Neyle,Neyliim,Nezanaraemi,Niaqi,Niebhdh,Niedh,Niewi,Niltibicx,Nirasse,Niremae,Niremage,Niremai,Nise,Nithsarbi,Nithsharb,Nolme,Nualam,Nuale,Nubicse,Nul,Nuliim,Nulme,Numaqe,Numate,Nume,Numes,Numse,Nuole,Nuome,Nyalam,Nyaliemm,Nyalimm,Nyaljhier,Nyaljim,Nyaljir,Nyebhmeas,Nylair,Nylme,Nylpho,Owummi,Pae,Pala,Palucqe,Pebleajam,Pemma,Pemme,Pesco,Peslatae,Peyrami,Peyre,Pharappame,Pharappe,Pharunime,Phorrac,Pilpisye,Pisle,Pislumarre,Pislumire,Pislumirre,Placqe,Planasawe,Plybimsae,Pretabe,Qaile,Qamje,Qamji,Qamtcu,Qaqa,Qassa,Qecanale,Qelam,Qelame,Qelim,Qelre,Qelurame,Qelurami,Qelure,Qenarre,Qesa,Qesamqe,Qesate,Qese,Qeselame,Qeselami,Qeseram,Qeseramqe,Qesge,Qeshelame,Qeshelami,Qeshi,Qeshilame,Qeshlam,Qeshriim,Qesilame,Qeslam,Qeslame,Qesu,Qiewo,Qiiram,Qiirem,Qiiwe,Qilcsam,Qimmibo,Qirro,Qlacsaeme,Qlacsaemi,Qlacsam,Qlacsame,Qlacsami,Qlacse,Qlacxsame,Qlainharb,Qlainharbi,Qlanharbi,Qlicximsae,Qlicximx,Qrele,Qrusarb,Qule,Qulmirae,Qumcsemxi,Qymajymbi,Rabae,Racdish,Race,Racirussi,Radilae,Raebeam,Raebem,Raeme,Raemi,Raic,Raice,Raici,Raicir,Raicirussi,Raicr,Rambe,Rara,Raraeme,Rarage,Rarase,Rari,Rarra,Rarre,Raru,Rawae,Raxe,Reane,Reisasae,Relace,Rele,Reuaci,Rewamae,Reyle,Reyne,Rie,Riem,Rima,Rime,Rimi,Rimyse,Riumae,Riumai,Riume,Riumsame,Riumuli,Riutebae,Robae,Ruli,Rulibeme,Ruliria,Russi,Ruyace,Ryaci,Ryacieth,Ryasjelb,Ryaxe,Rygxe,Rynamase,Ryry,Rysjelb,Rytae,Ryte,Ryxae,Sailmio,Sanie,Sedie,Semge,Seryrre,Sesaeme,Sesgeme,Shibe,Shie,Shilecae,Shilicae,Shilice,Shilici,Shiqre,Shule,Silice,Silix,Silixae,Silixe,Siqre,Site,Siubule,Sliece,Slyba,Sualiece,Symbi,Symbil,Taele,Taemmeas,Tamsae,Tara,Tcarre,Tcimji,Teas,Teaslae,Teaslaume,Teasram,Teccemble,Tecio,Teitarae,Telame,Telio,Telnim,Telre,Teluram,Telurami,Telure,Tembabe,Tenirae,Tesame,Teserame,Teshlam,Teshriim,Teslam,Teslame,Teslaume,Tetarae,Tetarai,Teuanhi,Teuaramm,Teuarfhaumm,Teuariemm,Thelrussi,Thiwummi,Thlacsaeme,Thlacsaemi,Thlacsam,Thlacsame,Thlacsami,Thlacse,Thlacsir,Titarae,Tlacsame,Tlame,Tlictimsae,Tolaete,Traubhme,Traume,Trelasae,Trele,Treybae,Triime,Trinimsae,Trubejh,Tucname,Tulame,Tulamme,Tulbyre,Tule,Tulmirae,Tumcsemsae,Tumcsemsame,Tumcsemse,Tumcsemxi,Tumtipse,Turynde,Ubarai,Ube,Ubhelmeas,Ueme,Ulcuroe,Ulfhreash,Ulme,Ulmes,Ulre,Ulreash,Ulrejh,Ulslym,Umule,Uranpae,Urawae,Urawe,Urje,Ussarai,Uume,Uumejh,Vadqi,Vaidqi,Varhirname,Varhirnami,Varne,Varro,Vembe,Verdylje,Versleyb,Waeslaz,Walej,Waljamae,Waqsulae,Waqsulage,Warne,Wase,Watsulae,Watsulame,Waulate,Wauremsi,Waurise,Wawaeme,Wecarate,Wemicce,Werbe,Wericqe,Werilae,Werilage,Werilai,Werimsame,Wile,Wilime,Wilumaqe,Wilumate,Wlima,Xacqe,Xarre,Xase,Xcemiss,Xcexce,Xcufae,Xcufaqe,Xcuqe,Xcyxca,Xcyxce,Xcyxcemme,Ximxa,Xirre,Xyxemme,Yctha,Ylce,Ylcir,Ylcyre,Yme,Yrlaqi,Yrra,Yrre,Ysi";
		String anpilayn1m = "Acabul,Acabulyc,Aceeq,Aceylyc,Acswem,Aelfhreash,Aelreash,Aemty,Aetunyc,Ailumanyc,Ajmesayc,Ajmesx,Ajmet,Amj,Amju,Amjunel,Amjurf,Ammutimsayc,Anli,Anlyc,Annemyir,Arai,Arric,Aucaf,Auciphyc,Auem,Aum,Aumesem,Aumir,Aumys,Aunhel,Awu,Awul,Axceq,Aycsamaemyc,Aycsamyc,Aycsyc,Ayraem,Ayray,Baba,Baelneab,Baelneas,Baelnyab,Baibilath,Bailq,Baisflaib,Baishirn,Baisil,Baislath,Baisnel,Balq,Bamy,Baumacai,Beali,Beasha,Belayc,Bele,Belejh,Beleth,Bellejh,Bem,Bema,Bemair,Bemairc,Bemys,Benhem,Bereth,Berio,Bero,Bewab,Bicabilayc,Bicabilesyc,Bicnumb,Biecym,Billo,Bilnus,Bimac,Bimic,Bimmac,Binisil,Birphamyc,Bisrif,Bitider,Bitrem,Biubesyc,Biwam,Bixcu,Biycbibas,Blacturr,Blejuc,Blejunal,Bulam,Bulem,Bulushiyc,Buly,Bumejh,Bumel,Bumer,Bumes,Bumesaemyc,Bumesyc,Bummtheb,Bummthebh,Bumuwem,Bunamaq,Bunamatyc,Bunhmerr,Bunmerr,Bunumquc,Bunusul,Buori,Buyjer,Bydhem,Bydhjherr,Byemi,Bylemc,Bynasly,Cabumayc,Caijdils,Caijflaib,Caijhelb,Caijnymb,Caijvelb,Caja,Cajacnymb,Cajnymb,Canaum,Canum,Carway,Carwayc,Carwicsil,Caushlym,Cazsyc,Cecthe,Cedirrayc,Cembul,Cemby,Cemoa,Cemtsayc,Ceny,Cenyir,Cerenum,Cerwesul,Chemi,Chenyc,Cheo,Chie,Chienyc,Ci,Cidecsaem,Cidecsaemyc,Cidicsoim,Ciefle,Ciejhbhe,Cielrec,Ciem,Ciemem,Cienec,Cienyc,Ciethmerr,Ciethremm,Cilefan,Cilephamyc,Ciljay,Ciljhia,Cilwesayc,Cimem,Cipp,Cippir,Cithmerr,Ciualci,Ciucenh,Ciwilam,Csaufem,Csem,Csifem,Csifemc,Csiffim,Csiphem,Csiraem,Culam,Culim,Culrio,Cune,Cunhealri,Cviimio,Cwim,Cxarelb,Cxarwicxsil,Cxedurtc,Cyadhmi,Cyadmi,Dealli,Decsaem,Dellai,Delle,Dellfamb,Dellfhaumm,Dello,Delme,Delmedec,Delser,Delshuruneyc,Demba,Depsacs,Depsacse,Derams,Derbyl,Derexc,Dgulm,Dieleth,Dies,Diesyc,Dileth,Dilmb,Dilmes,Dilmhelb,Dils,Dilserem,Dilshurb,Dilslen,Dilsuq,Dim,Dimaenam,Dimajmyc,Dimbaqc,Dimbijyx,Dimgenam,Dimibaqs,Dimibatsyc,Dimibiq,Dimmu,Dimti,Dire,Dlaem,Dlebeth,Dlebim,Dlebo,Dlem,Dliembem,Dlimbem,Dlimbemyc,Dlimmem,Dlujem,Dlymu,Dujbem,Dulac,Dumafesayc,Dumafet,Dumafex,Durbaxcel,Dusumb,Dylqhelb,Dylqhels,Dylthelb,Eabem,Eamblay,Eambliec,Earam,Eararr,Eben,Eberdils,Ebhenh,Ebirdils,Ebiubesyc,Eblaem,Ebulgem,Eburf,Eddem,Edir,Edlehen,Eijabayc,Eimjyc,Ejucsum,Elacxsab,Elber,Elbjher,Elimb,Elmbs,Elmflaib,Elmi,Elmurb,Elnam,Elpeb,Elsgunc,Elshyl,Elsyl,Elsylc,Elum,Emblac,Emblec,Emblia,Embliec,Embligc,Embul,Emcirn,Emcjel,Emecxsex,Emesuragc,Emjhir,Emjiryc,Emjyc,Emlea,Emser,Emsum,Endlyc,Enebiyc,Enedarac,Enemb,Enembyc,Enemsayc,Enesul,Enesyc,Enhreuadh,Equc,Eram,Erdem,Erdilat,Erdilath,Erdils,Erdliths,Erdo,Erecsel,Ereguc,Ereuac,Erflib,Erfumc,Eriz,Erizac,Erizembil,Erizembly,Ernuc,Eruac,Eruocayc,Ervam,Esemeci,Essare,Ethan,Eubh,Eubhejem,Eubhem,Eumjhyc,Eyjycs,Eyjycsam,Eyjycsc,Eylir,Ezir,Fabirac,Faethle,Faethme,Faisi,Falnamyc,Famdel,Famdell,Famm,Fammaem,Fammdel,Fammdell,Fammejem,Fammem,Fammijem,Fammim,Famreo,Famrio,Famsem,Faradils,Farap,Farapc,Farram,Faum,Faumm,Faummdelle,Faummdhell,Faummem,Faummrejh,Faummsem,Fedaem,Fedu,Felkyhel,Femi,Ferq,Fethsme,Feurem,Fiabhran,Fiabhranabh,Fiatham,Ficsil,Fielbulthe,Fieljhec,Fieljher,Fielthel,Fila,Filba,Filbamemb,Filimt,Filjer,Filjyc,Fillysayc,Filqu,Firamyc,Firan,Firataemyc,Firatayc,Firaz,Fitham,Flablahc,Flaibhirn,Flaibhurb,Flaibinemm,Flaiblath,Flajabaemyc,Flajoic,Flasx,Flatac,Flemq,Flemtactyc,Flemx,Flib,Flig,Freashla,Fremm,Fremmem,Freway,Frulaem,Frulam,Frulamyc,Frulimsamyc,Frulimsayc,Frullo,Fryllo,Fulsymesyc,Fyrjimsayc,Fyrup,Gelresh,Gem,Gema,Gemac,Gemaqe,Gemtca,Gemuc,Geqed,Gequd,Getudyc,Gexipc,Gilinaec,Gimta,Gimu,Gucif,Guciph,Gucqe,Gucs,Guemmic,Guethan,Guhem,Guhemm,Guhemmic,Gulj,Gumec,Gumesem,Gumeshem,Guthan,Guthim,Guthin,Guxca,Guxcif,Guxcye,Gycsyc,Gylac,Gyljim,Gyraem,Gyrayc,Hailumonyc,Hamlath,Harbidils,Harbidlemb,Hardils,Hejim,Helerb,Helerend,Helsnemm,Helsnys,Helsvaj,Helsvam,Hemc,Hemmic,Hemqi,Hiamil,Hiamlath,Hiamu,Hiamx,Hiaqu,Hidil,Hiladils,Hildils,Hilnemm,Hilnimijarb,Himblaq,Himlaq,Himmamj,Hirflaib,Hirji,Hirnflaib,Hirnys,Hirnysh,Hulae,Hulcs,Hulesay,Hulie,Humulamyc,Humulayc,Humulesyc,Hydils,Hydilsyc,Hyju,Hymul,Hyndils,Hyppils,Iadhal,Iadhiel,Iamla,Ianham,Ibem,Ibi,Ibnymb,Ibwam,Ibwelb,Ibyelb,Ibyelbc,Iddi,Idilhelb,Iebdhelb,Iemme,Ienum,Ienumm,Iethemm,Ijum,Ilaq,Ilat,Ilath,Ilbnemm,Ilcqami,Ilhelb,Ilmcs,Ilmu,Ilvam,Ilwam,Ilwamc,Imbe,Imbli,Imjir,Imjirdils,Imme,Inar,Inaraem,Inemyir,Inilimsayc,Innilath,Inojbayc,Iphicayc,Iqqihelb,Iqqihelbs,Iraec,Irajayc,Iriq,Irnu,Isiri,Isxir,Itqdils,Itqels,Itqhelb,Itqhels,Itqihelb,Iuam,Iujhem,Iverb,Iwils,Iycsethayc,Iyjim,Jacdils,Jardils,Jarluo,Jecpel,Jedamyc,Jedlair,Jedlairc,Jedul,Jeldhem,Jelwem,Jerrejhil,Jerrthudhel,Jewlar,Jexca,Jhimebai,Jhiuljhi,Jiddils,Jidhelb,Jielers,Jieluab,Jiils,Jilb,Jilerb,Jilflaib,Jilhelb,Jilhelbs,Jilhurb,Jilium,Jiljiro,Jilju,Jilmus,Jils,Jilu,Jilumsayc,Jilurb,Jilwec,Jilyrf,Jirrils,Jiulj,Jiuljagc,Jiuljc,Jiulji,Jixe,Jlajulagc,Jlajuli,Jlebo,Jliejual,Jlijul,Jouljo,Jouxu,Joyla,Joyre,Judem,Jufleabh,Jussctherq,Jussflaib,Jussharf,Jusshelb,Jusshurb,Jussraid,Jussrud,Jyabu,Jycsef,Jycsew,Jycsewc,Jycxsew,Jymbehel,Jymshil,Jymsil,Jymslen,Kyalam,Kyalamyc,Kyamm,Lacsielb,Laejem,Laem,Lahelbc,Laqelb,Lathelb,Laujhmem,Laulbem,Leamil,Leanumbc,Leanymb,Leby,Lefeir,Leffeir,Lejhmerr,Lepheir,Lerf,Lerph,Lexwem,Liam,Liamhelb,Liamhurb,Liamil,Lianymb,Libnumb,Libnymb,Lielbim,Lienemm,Limesyc,Limi,Linajayc,Linyc,Lisu,Loem,Luadielb,Luburf,Luda,Ludils,Ludilsc,Lujil,Lulai,Lulbem,Lulo,Lumem,Luneiyc,Lunem,Lunemyc,Luremb,Lurf,Luthyc,Luvem,Lyba,Lybajil,Lyburf,Lyeabhla,Lyeabla,Lyeala,Lyebh,Lyebhem,Lyelt,Lyiba,Lypils,Lypliths,Maerr,Mamaem,Maqrec,Maqreyc,Maqure,Maquregc,Maqureyc,Matqureyc,Matu,Maturei,Matureyc,Maty,Matycul,Mautrec,Meltaccyc,Membul,Meserayc,Meuaci,Meunhem,Mexelayc,Mexelimyc,Miar,Miry,Mityrea,Miwem,Muldils,Murem,Murreaj,Naca,Nacqe,Nahea,Nahear,Nahearc,Nahease,Nahero,Nailwerbac,Naltie,Nalum,Naqce,Naqirac,Naqruc,Narem,Nasate,Natha,Natheir,Nathier,Nathir,Nealsam,Neamtham,Neasay,Nehum,Nejhmyc,Nejmyc,Nelaem,Nelam,Nelayc,Nelq,Nelqyc,Nelqycc,Nelsam,Nelsum,Neltec,Neltir,Neltirr,Neltirryc,Neltu,Nelvam,Nelwam,Nelxirr,Nemflaib,Nemflib,Nemmaz,Nemy,Nemyc,Nemyir,Neretho,Nershi,Nersi,Neshac,Neshaec,Neshyam,Nesi,Nesia,Nesoec,Nessaec,Nesshaec,Nessheyc,Neurchiethremm,Neylasayc,Neylyc,Nez,Nezanaraem,Niamelb,Niamhelb,Niami,Niamleb,Niamu,Nierrem,Nilsim,Nimmu,Nirrem,Nubicsyc,Nuci,Nulasx,Nulat,Nuxic,Nyalac,Nyalibeth,Nyaliebheth,Nyalthilseth,Nylbuth,Nylluyjh,Nylpho,Nylsejh,Nylthebh,Owu,Pacsa,Pacse,Paelec,Parad,Payc,Pebbo,Pebleaj,Pebleat,Pecsul,Pecter,Pectherac,Pelcafer,Pemqlex,Per,Peslaq,Peslatayc,Peslatq,Pewarc,Peyr,Pharapp,Phiran,Phirem,Piebel,Pilijlamyc,Pisa,Pisil,Pislate,Pisli,Pisly,Pislyc,Planasawyc,Planyc,Pluamcaec,Plucpilyc,Plybimsayc,Pretabyc,Punparay,Pur,Purba,Qailem,Qailum,Qalarc,Qaraem,Qarraem,Qea,Qecanal,Qecpel,Qecpelc,Qegisem,Qelcsim,Qelr,Qelrnemm,Qeltca,Qeluro,Qemi,Qeo,Qeoisem,Qernem,Qexanal,Qexnil,Qiem,Qiemi,Qiifi,Qiijem,Qiimem,Qirem,Qirinim,Qirro,Qiwam,Qiwem,Qlacsaemc,Qlacsepc,Qlacsuf,Qlacxsaem,Qmys,Qolem,Qreec,Qreybagc,Qreyc,Qrinimc,Qulb,Quldamaem,Quldr,Qulmir,Qumcsemsam,Qumleb,Quppemo,Qurnem,Quruc,Qurunem,Qyls,Qymadils,Qymu,Radilayc,Radulayc,Raen,Ramyc,Raway,Recxru,Redhlec,Reguc,Relc,Remxu,Rendils,Rennils,Renpliths,Reta,Rethsme,Reujheali,Rexel,Reylimsay,Reylimx,Reylyc,Ridiliths,Rielo,Riethreamm,Rimmels,Rimx,Riu,Rium,Riumayc,Riumelb,Riumhelb,Riupurb,Riutebayc,Riwimsi,Rulamt,Rulemb,Rulems,Rulimx,Rultem,Rulttem,Rumem,Runem,Runnem,Rushel,Ruthreamm,Ruthremm,Ryasjil,Ryaspurb,Rybac,Rybjil,Ryburf,Rybvaj,Rybwajc,Ryjheabh,Rypyc,Ryqec,Ryqetc,Rysx,Rytaem,Ryte,Rytec,Sadilay,Sadul,Sadult,Saelmem,Saelmeth,Saibinemm,Sailmem,Sailmio,Sajhi,Sajhielmem,Sajhielmeth,Sajilmem,Sajilmeth,San,Sanu,Sanushiyc,Sanusia,Sarr,Sarru,Saru,Sawebel,Sebhj,Sebhjem,Sebj,Senec,Shainu,Sharu,Shiubul,Shiuphar,Shulcsim,Shuldim,Shunec,Siaji,Siajyi,Siejyi,Siubul,Siubulc,Sleaem,Sleyjuss,Slieceth,Sualbhierdheth,Subul,Sudaec,Suer,Sulam,Sulcsim,Suldim,Suma,Suna,Sunc,Sune,Sunec,Sybul,Syesher,Sylruyjh,Tael,Taelbhe,Taelem,Taem,Taemem,Tameib,Taplaem,Tarraem,Tarram,Taumeubh,Tcede,Teaisemyc,Tealdli,Teammieth,Tebujem,Tecio,Tehal,Teher,Teicelayc,Teiricsac,Teiricsamyc,Telcsim,Teldlio,Teldlo,Telio,Tellur,Tellurr,Telr,Telsheth,Telur,Tembabyc,Terazsyc,Terdheth,Terracsyc,Terrazsyc,Terujilyc,Terwejh,Teseram,Tesheal,Teshem,Tesher,Tesheual,Teuanham,Teurem,Thlacsaem,Thlacsaemyc,Thlacsai,Thlacso,Thlacsuph,Thlacsuphulyc,Tieldherr,Tierrejh,Tierreth,Tierrethem,Timmisaj,Tixel,Tlacsa,Tlacsaem,Tlictimc,Tlictimsayc,Tolaetyc,Tranetyc,Trelyc,Tremto,Treybay,Treyc,Trinimc,Trinimsayc,Tuariem,Tubo,Tucnam,Tucsam,Tucsate,Tucsethi,Tucsir,Tuinjiam,Tulb,Tuldamaem,Tuldamaemyc,Tulmir,Tulmiray,Tulmirayc,Tulnet,Tumcsemc,Tumcsemsam,Tumcsemsamyc,Tumcsemsayc,Tumem,Tumerr,Tumla,Tumleb,Tumm,Tummul,Tumrio,Tumrish,Tumthudhel,Tumthyl,Tumul,Tunhjhem,Tunhjherr,Tunjem,Tunjer,Tunjerr,Turam,Turinem,Turn,Turnem,Turyn,Turynde,Turyndem,Turyndemyc,Tuver,Tyem,Uacam,Uba,Ubhlem,Ublem,Ubum,Uchiim,Ucqel,Ucqelc,Uctel,Ucverb,Ucxqel,Uldem,Ulem,Uler,Ullam,Ulsvam,Urawil,Uref,Ushnel,Usnel,Ussnel,Ussu,Ussunel,Ussuqel,Utsewaem,Uvim,Uwabay,Vaidi,Vairemb,Vamflaib,Van,Varflaib,Varhirn,Varra,Varro,Vasurb,Verbinel,Verbu,Vershil,Versil,Viccir,Vilmil,Vilshil,Vimbir,Vimbiram,Vimxicreyc,Vimxir,Viremb,Visxir,Vubem,Vurf,Vurfjemj,Vurflen,Vusem,Vyrf,Wab,Wabe,Wacwerbac,Waesul,Waljar,Waljaray,Waljarayc,Wamti,Wamtimsayc,Wamxims,Wamximx,Waqsul,Wara,Warac,Warhirn,Warhirnc,Warnuc,Waserac,Watsul,Watsulamyc,Watsulayc,Waulir,Wawaemyc,Wecarate,Wecari,Wera,Werbac,Werilaem,Werilagc,Werilay,Werimsam,Wias,Wicsil,Wieticrew,Wilaccanyc,Wimtir,Wreb,Wurbinelc,Wurqil,Xcaje,Xcajnumb,Xcundul,Xcurs,Xipholamyc,Xursem,Yamciemm,Yarraen,Yarriej,Ybu,Yeashmi,Yira,Ylc,Ylcamyc,Ylcyc,Yldem,Yldemyc,Yratq,Yrlath,Yrra,Yrsem,Ysx,Yvi,Zewil";
		String anpilayn2 = "Amcsiayc,Atarayc,Babayc,Barrayc,Bicsatayc,Bitynayc,Bizcayc,Buccimayc,Bunasayc,Bylumayc,Byttayc,Cabumayc,Carayc,Cassayc,Cedytayc,Cerrycsayc,Cerumayc,Cerwayc,Ciayc,Cicsayc,Ciljayc,Cilsulayc,Cilwarayc,Cimmayc,Cimsayc,Cinplumayc,Cipsanayc,Cipyltayc,Cipymayc,Citymbamayc,Citymbayc,Cizsarayc,Cizsayc,Cpylayc,Csesarayc,Csesayc,Csilsamayc,Ctladumayc,Culmesayc,Cutirrayc,Cyibayc,Cyrpatayc,Dedybayc,Deidayc,Deldesayc,Dellayc,Demsayc,Derwimsayc,Disaraimyc,Disytayc,Dlyssayc,Dlyttayc,Drembayc,Druccayc,Dyllaimyc,Dyttyriayc,Ecamayc,Edylayc,Eibamayc,Eidysayc,Einarayc,Eirayc,Ekyarrayc,Elcamayc,Ellayc,Elnimayc,Elsulayc,Emmayc,Emsacsayc,Emsayc,Emsumayc,Enesayc,Eppyriayc,Erdemayc,Erdesayc,Erritsayc,Esarayc,Esayc,Esiayc,Eslayc,Eslumayc,Essayc,Etarayc,Ettayc,Etturiayc,Ewabayc,Ewasyc,Eycumayc,Eyfabayc,Eylayc,Eylirayc,Ezayc,Febayc,Fedayc,Feimayc,Ferilayc,Fewumayc,Ficsamayc,Frewamayc,Frewayc,Frewumayc,Frulabayc,Frulayc,Frulumayc,Fyfayc,Fylayc,Fymbemyc,Fyrtamayc,Fyrwayc,Gymayc,Gyrayc,Gywimsayc,Halsayc,Hilimmayc,Hilnamayc,Hirwayc,Hirwisayc,Hucabayc,Hucsarayc,Hulesayc,Hulsimcayc,Ijmesayc,Ikyasayc,Ipabayc,Jedamayc,Jerilayc,Jewayc,Jijemayc,Jirrayc,Jlemayc,Jlesabayc,Jlesayc,Kyalamayc,Kyamtsarayc,Kyamtsayc,Ledalayc,Lycumayc,Lyfayc,Lyflayc,Lysarayc,Majabayc,Majarayc,Mammayc,Mapayc,Mecimmayc,Meiwayc,Minisulayc,Mipayc,Muldemyc,Muwayc,Mynilayc,Namatayc,Namytayc,Narumayc,Neirayc,Neitarayc,Nelayc,Neltayc,Nemarayc,Nemrayc,Nenarayc,Nerrayc,Nesayc,Netlamayc,Nezanayc,Niccaimyc,Nimimayc,Ninnayc,Nisarayc,Nubayc,Nyllayc,Nymayc,Nymesayc,Nytayc,Pacimsayc,Pactayc,Pamelayc,Peicimsayc,Pepalayc,Pepamayc,Pepayc,Perpirrayc,Pibayc,Pictimmayc,Pirslecayc,Pisarayc,Pisarrayc,Pisirrayc,Pislumayc,Pramayc,Pretabayc,Preysayc,Prusayc,Pucsynayc,Pulsayc,Pumsabayc,Pumsayc,Punparayc,Punpiayc,Punpsamyc,Punpumayc,Pupabayc,Purrayc,Pusasayc,Pydratayc,Pypayc,Pyrru,Radylmayc,Ratamayc,Rawayc,Redaimyc,Redilayc,Reflimayc,Reirayc,Reisulayc,Relsayc,Renplumayc,Ruliayc,Rumjamayc,Rurrayc,Rycayc,Rysesayc,Rytarayc,Rytayc,Rytlisayc,Ryttiayc,Sasaibayc,Sasamayc,Sasayc,Sebayc,Sematayc,Sernybayc,Silsamayc,Sissabayc,Sissaimyc,Sissayc,Slidesayc,Slidirrayc,Slidremyc,Slinirrayc,Sylyrrayc,Syrrayc,Syttayc,Tacpayc,Tamtayc,Tarmayc,Tatiliayc,Teccayc,Teibatayc,Teicayc,Teicimmayc,Teicisayc,Teicumayc,Teicyrimyc,Teilirrayc,Teipecayc,Teipelayc,Teirayc,Teislumayc,Teitame,Teitarayc,Teitayc,Telacsemayc,Telayc,Telwarayc,Temabayc,Temamayc,Temayc,Temsarayc,Temsayc,Temyriayc,Temysayc,Tenarayc,Tenarrayc,Tenirayc,Teplimayc,Terabayc,Terewayc,Terpylmayc,Terwacayc,Terwimsayc,Tiaumayc,Treybayc,Trubayc,Truirayc,Truwayc,Tryarayc,Trymsayc,Tuaibayc,Tuctumayc,Tulbayc,Tulmirayc,Tulymtemayc,Tumcabayc,Tumcimsayc,Tunamayc,Tuttiayc,Tylayc,Tylsayc,Ulemayc,Upcayc,Uppayc,Urtamayc,Usetarayc,Utsewayc,Wabytayc,Wacirrayc,Wadabayc,Wadayc,Wadimayc,Walabayc,Walayc,Wamatayc,Wapcemayc,Wapcsemyc,Wasirrayc,Waslywayc,Watslatayc,Wawaemyc,Weccimayc,Wejaumayc,Wejimmayc,Wejmayc,Welayc,Werilayc,Wesamayc,Wibayc,Wicmayc,Wilemayc,Wilitymbayc,Wiljamayc,Wiljarayc,Wirayc,Wisylayc,Wulimyc,Wurejamayc,Wurtesayc,Wurycayc,Wurycimme,Wurycimyc,Wurynmayc,Yljyremayc,Yndlayc,Yndlimayc,Ynnabayc,Yrpayc,Yyrayc";
		String anpilayn3f = "Aceyle,Aycsame,Aytymbe,Baumocae,Bicabilae,Bicabilese,Birphame,Bumese,Bunamate,Cabumae,Cadorre,Carwae,Cerweslaz,Cilephame,Cilime,Codarre,Cpilemsae,Cthurecsate,Currinmae,Dadaeme,Deldele,Diese,Dieslaz,Dimajme,Dimibatse,Efle,Emesurae,Emjire,Enedarae,Enembe,Enese,Eylie,Firame,Firatae,Firataeme,Firatasec,Flemtacte,Frulame,Frulimsae,Frulimsame,Fulsymese,Guhemme,Gycsame,Humulae,Humulame,Humulese,Irajae,Kyalame,Lijame,Lijyre,Limese,Lucerae,Luneme,Meltacce,Meserae,Neljelase,Neslume,Neyle,Niremae,Nubicse,Numate,Pae,Peslatae,Pilpisye,Pislumarre,Planasawe,Plybimsae,Pretabe,Qesilame,Radilae,Reisasae,Reyle,Riumae,Riumsame,Riutebae,Shilecae,Telame,Tembabe,Thlacsaeme,Tlictimsae,Tolaete,Trelasae,Trele,Trinimsae,Tumcsemsae,Tumcsemsame,Turynde,Urawe,Waeslaz,Watsulae,Watsulame,Wauremsi,Wawaeme,Wilime,Wilumate,Ylce,Ylcyre";
		String anpilayn3m = "Acabulyc,Aceylyc,Aetunyc,Ailumanyc,Ajmesayc,Ammutimsayc,Auciphyc,Aycsamaemyc,Aycsamyc,Aycsyc,Bicabilayc,Bicabilesyc,Birphamyc,Biubesyc,Biycbibas,Bulushiyc,Bumesaemyc,Bumesyc,Bunamatyc,Bylemc,Cabumayc,Carwayc,Carwicsil,Cazsyc,Cedirrayc,Cemtsayc,Cerwesul,Cidecsaemyc,Cilephamyc,Cilwesayc,Depsacse,Diesyc,Dimajmyc,Dimibatsyc,Dumafesayc,Ebiubesyc,Eijabayc,Emjiryc,Enebiyc,Enedarac,Enembyc,Enemsayc,Enesul,Enesyc,Fabirac,Falnamyc,Fillysayc,Firamyc,Firataemyc,Firatayc,Flajabaemyc,Flemtactyc,Frulamyc,Frulimsamyc,Frulimsayc,Fulsymesyc,Fyrjimsayc,Getudyc,Guemmic,Guhemmic,Gycsyc,Humulamyc,Humulayc,Humulesyc,Inilimsayc,Inojbayc,Iphicayc,Irajayc,Iycsethayc,Jedamyc,Jilium,Jilumsayc,Kyalamyc,Limesyc,Linajayc,Luneiyc,Lunemyc,Meltaccyc,Meserayc,Mexelayc,Mexelimyc,Nejmyc,Neylasayc,Neylyc,Nubicsyc,Payc,Pecsul,Pectherac,Peslatayc,Pilijlamyc,Planasawyc,Planyc,Plucpilyc,Plybimsayc,Pretabyc,Radilayc,Radulayc,Reylyc,Riu,Riumayc,Riutebayc,Rypyc,Teaisemyc,Teicelayc,Teiricsac,Teiricsamyc,Tembabyc,Terazsyc,Terracsyc,Terrazsyc,Terujilyc,Thlacsaemyc,Thlacsuphulyc,Tlictimc,Tlictimsayc,Tolaetyc,Tranetyc,Trelyc,Trinimc,Trinimsayc,Tuldamaemyc,Tumcsemc,Tumcsemsamyc,Tumcsemsayc,Turynde,Turyndemyc,Waesul,Waljarayc,Wamtimsayc,Waserac,Watsul,Watsulamyc,Watsulayc,Wawaemyc,Wilaccanyc,Xipholamyc,Ylcamyc,Ylcyc,Yldemyc";
		String eolsungf = "Aada,Aamu,Aava,Abelone,Ada,Adele,Agata,Agathe,Agda,Agnes,Agneta,Agnete,Agnetha,Agnethe,Aila,Aili,Aina,Aino,Alberte,Ale,Alex,Alexandra,Alfhild,Aliisa,Alisa,Alli,Alva,Alvilda,Amanda,Andrea,Ane,Anika,Anita,Anja,Anna,Anna-liisa,Annbjørg,Anne,Anneli,Annelie,Annelise,Annette,Anni,Anniina,Annika,Anniken,Annikki,Annukka,Ansa,Antonia,Anu,Arja,Arnbjörg,Arnbjørg,Arnborg,Aslaug,Aslög,Asløg,Asta,Astrid,Audhild,Aune,Aurora,Aðalbjörg,Barbro,Beata,Beatrice,Benedikte,Bengta,Bente,Bergliot,Bergljot,Bergljót,Berit,Bine,Birgit,Birgitta,Birgitte,Birita,Birte,Birthe,Björg,Björk,Bjørg,Bodil,Borghild,Borghildr,Borghildur,Brit,Brita,Britt,Britta,Brynhild,Brynhildr,Brynhildur,Brynja,Caja,Cajsa,Camilla,Carin,Carina,Carita,Carola,Carolina,Caroline,Catharina,Cathrine,Catrine,Cecilia,Cecilie,Charlotta,Charlotte,Christa,Christin,Christina,Christine,Cilla,Cille,Dagmar,Dagny,Dagný,Dagrun,Ditte,Dorete,Dorit,Dorotea,Dorothea,Dorte,Dorthe,Ea,Ebba,Edda,Edit,Edith,Eerika,Eeva,Eevi,Eija,Eir,Eira,Eleonoora,Eleonor,Eleonora,Elfa,Eli,Eliina,Eliisa,Elin,Elina,Elisa,Elisabet,Elisabeth,Elise,Ella,Elli,Ellinor,Elsa,Else,Elva,Elísabet,Embla,Emelie,Emilia,Emilie,Emilía,Emma,Emmi,Enni,Erica,Erika,Erja,Erle,Erna,Essi,Ester,Esteri,Eva,Eveliina,Evelina,Eydís,Fanni,Felicia,Filippa,Frea,Frederikke,Fredrika,Freja,Freya,Freyja,Frida,Frigg,Friðrika,Fríða,Frøya,Gabriella,Gerd,Gerda,Gina,Gittan,Gitte,Greta,Grete,Grethe,Grid,Gro,Gry,Grímhildr,Gróa,Gudrun,Gull,Gun,Gunborg,Gunda,Gunhild,Gunhilda,Gunilla,Gunn,Gunna,Gunnel,Gunnhild,Gunnr,Gunnvor,Gunvor,Guðlaug,Guðrún,Gyda,Halldóra,Hanna,Hannah,Hanne,Hannele,Hedda,Hedvig,Hege,Heidi,Heidrun,Heiðrún,Hel,Heleena,Helena,Helene,Helga,Heli,Helka,Hella,Helle,Hellä,Helmi,Henna,Henrietta,Henriette,Henriikka,Henrika,Henrike,Hilda,Hilde,Hildegard,Hildr,Hildur,Hilja,Hillevi,Hjördis,Hjördís,Hjørdis,Huld,Hulda,Ida,Idun,Iida,Iina,Iines,Iiris,Ilma,Ilmatar,Ilona,Ilta,Impi,Ina,Inga,Inge,Ingebjørg,Ingeborg,Ingegerd,Ingegärd,Inger,Ingrid,Ingvild,Inka,Inkeri,Irene,Irina,Iris,Irja,Irma,Isabella,Iðunn,Jaana,Jacobine,Janina,Janna,Janne,Jannicke,Jannike,Jeanette,Jenna,Jenni,Jennie,Jennifer,Jenny,Jessica,Johanna,Johanne,Jonna,Jorun,Jorunn,Josefiina,Josefina,Judit,Julia,Julie,Jytte,Jóhanna,Jóna,Kaarina,Kai,Kaia,Kaija,Kaisa,Kaj,Kaja,Kajsa,Kamilla,Karen,Kari,Karin,Karina,Karine,Karita,Karla,Karoliina,Karolina,Karoline,Kata,Katariina,Katarina,Katharina,Kathrine,Kati,Katja,Katri,Katriina,Katrin,Katrina,Katrine,Kerstin,Kerttu,Kia,Kielo,Kiira,Kine,Kirsi,Kirsikka,Kirsten,Kirsti,Kirstine,Kjellfrid,Kjersti,Kjerstin,Klara,Kris,Krista,Kristiina,Kristin,Kristina,Kristine,Kristjana,Kristín,Kukka,Kylli,Kyllikki,Lahja,Laila,Laura,Lea,Leena,Lempi,Lena,Lene,Liina,Liisa,Liisi,Lilja,Lilli,Lilly,Lina,Linda,Line,Linn,Linnéa,Lis,Lisa,Lisbet,Lise,Liselott,Liselotte,Liss,Lissi,Liv,Lone,Lotta,Lotte,Lottie,Louhi,Louise,Loviatar,Loviisa,Lovisa,Lovise,Lucia,Lumi,Lydia,Lykke,Lyydia,Lyyti,Láilá,Lára,Lærke,Maaria,Maarika,Maarit,Madeleine,Magda,Magdalena,Magdalene,Magdalone,Magnhild,Maija,Maiken,Maire,Maja,Majken,Malena,Malene,Malin,Manu,Maren,Margareeta,Margareta,Margarethe,Margit,Margrete,Margrethe,Margrét,Mari,Maria,Marianne,Marie,Marika,Marina,Marit,Marita,Maritta,Marja,Marjaana,Marjatta,Marjo,Marjukka,Marjut,Marketta,Marna,Marta,Marte,Martha,Marthe,Martina,Martine,Martta,María,Mathilda,Mathilde,Matilda,Matleena,Merete,Meri,Merit,Merja,Meta,Mette,Mia,Michaela,Mielikki,Miia,Miina,Mikaela,Mikkeline,Milla,Milly,Mimmi,Minna,Minttu,Mirja,Mirjam,Mirjami,Moa,Mona,Monika,My,Márjá,Märta,Mæja,Nanna,Nea,Niina,Nina,Njála,Noora,Nora,Oili,Olga,Olivia,Oona,Orvokki,Ottilia,Paula,Pauliina,Paulina,Pauline,Pernilla,Pernille,Petra,Petronella,Pia,Pihla,Piia,Pilvi,Pinja,Piritta,Pirjo,Pirkko,Priita,Pála,Päivi,Päivä,Raakel,Ragna,Ragnheiður,Ragnhild,Ragnhildur,Rakel,Randi,Rauha,Rebecca,Rebecka,Rebekka,Reeta,Reetta,Regina,Regine,Reidun,Renate,Riika,Riikka,Riina,Riitta,Rika,Rikke,Rita,Ritva,Robin,Ronja,Rosa,Runa,Rut,Ruth,Ruut,Saana,Saara,Saga,Saija,Salli,Sandra,Sanna,Sanne,Sanni,Sara,Sari,Sassa,Satu,Seija,Selma,Senja,Sibylla,Sif,Sigfrid,Signe,Signy,Signý,Sigrid,Sigrun,Sigrún,Siiri,Silja,Silje,Sille,Sini,Sinikka,Siri,Sirpa,Sisko,Siv,Skaði,Skuld,Sofia,Sofie,Sohvi,Soile,Soili,Solfrid,Solveig,Solvej,Solvig,Sonja,Stefanie,Stiina,Stina,Stine,Sunniva,Suoma,Susann,Susanna,Susanne,Suvi,Svana,Svanhild,Svanhildr,Svanhildur,Svea,Sylvi,Sylvia,Synne,Synnöve,Synnøve,Säde,Sølvi,Taika,Taimi,Taina,Tanja,Tarja,Taru,Tatiana,Tatjana,Tea,Teija,Tellervo,Teodora,Teresa,Terese,Teresia,Terhi,Terttu,Tessan,Thea,Theresa,Therese,Theresia,Thora,Thorborg,Thyra,Tiia,Tiina,Tilda,Tilde,Tine,Toini,Tone,Tora,Torbjørg,Torborg,Tordis,Torhild,Toril,Torill,Torny,Torø,Tova,Tove,Trine,Trude,Tuija,Turid,Tuula,Tuuli,Tuulikki,Tuva,Tyra,Tyyne,Tähti,Ulla,Ulrica,Ulriikka,Ulrika,Ulrikke,Unn,Unnur,Urd,Ursula,Valdís,Valpuri,Vanamo,Vanja,Vappu,Varpu,Veera,Vellamo,Vendela,Venla,Vera,Verdandi,Veronika,Veslemøy,Vibeke,Victoria,Vieno,Vigdís,Viivi,Viktoria,Vilhelmiina,Vilhelmina,Vilja,Vilma,Viola,Virginia,Virva,Vita,Viveka,Vivi,Vivian,Vuokko,Ylva,Yvonne,Áile,Ása,Ásdís,Áslaug,Ásta,Ástríður,Ågot,Åsa,Åse,Øydis,Þórdís";
		String eolsungm = "Aabraham,Aadolf,Aage,Aapeli,Aapo,Aarne,Aatami,Aatos,Aatto,Aatu,Acke,Adam,Adolf,Adrian,Ahti,Aimo,Aki,Aksel,Akseli,Aku,Albert,Albin,Ale,Aleksander,Aleksanteri,Aleksi,Alex,Alexander,Alf,Alfr,Alfred,Alpertti,Altti,Alv,Alvar,Alvis,Amund,Anders,Andor,Andreas,Anselmi,Ansgar,Anssi,Antero,Anton,Antti,Anttoni,Ari,Armas,Armo,Arne,Arnfinn,Arnór,Arnþór,Aron,Arthur,Arto,Arttu,Artturi,Artur,Arvid,Arvo,Asbjörn,Asbjørn,Asgeir,Asger,Ask,Askr,Atte,August,Aukusti,Aulis,Axel,Aðalsteinn,Balder,Baldr,Baldur,Bendt,Benedikt,Bengt,Benjamin,Benjamín,Bent,Bernhard,Bernt,Bertil,Birger,Birgir,Bjarke,Bjarne,Bjarni,Bjarte,Bjartur,Bjoern,Björn,Björne,Bjørn,Bo,Bosse,Brynjar,Bård,Börje,Cai,Caj,Carl,Casper,Christen,Christer,Christian,Christoffer,Claes,Claus,Dag,Dagfinn,Dagur,Dan,Daniel,Danne,Daníel,David,Ebbe,Edvard,Edvin,Eelis,Eemeli,Eemil,Eerik,Eerikki,Eero,Eetu,Egil,Egill,Eilert,Einar,Eindride,Eino,Eirik,Eiríkur,Eivind,Ejvind,Elias,Elis,Eljas,Elof,Elov,Eluf,Elvar,Emanuel,Emil,Endre,Enok,Ensio,Eric,Erik,Erkki,Erland,Erlend,Erlendur,Erling,Erlingur,Erno,Ernst,Esa,Esben,Esbjörn,Espen,Even,Eysteinn,Eyvindur,Fannar,Felix,Ferdinand,Filip,Finn,Finnur,Flemming,Folke,Frans,Frederik,Fredrik,Frej,Frey,Freyr,Fridtjof,Fritjof,Friðrik,Frode,Gabriel,Gandalf,Geir,Georg,Gerhard,Gjord,Gjurd,Godtfred,Gottfrid,Greger,Gregers,Gudbrand,Gudmund,Gulbrand,Gunnar,Gunnarr,Gunne,Gustaf,Gustav,Göran,Gösta,Göstav,Gøran,Haakon,Hagen,Haldor,Hallbjörn,Halldor,Halldór,Halle,Hallvard,Halstein,Halsten,Halvar,Halvard,Halvdan,Halvor,Hampus,Hanne,Hannes,Hannu,Hans,Harald,Haraldur,Harri,Hasse,Heikki,Heino,Helge,Hemming,Henning,Henri,Henrik,Henrikki,Herleif,Herman,Hermanni,Hesekiel,Hinrik,Hjalmar,Hjörtur,Holger,Hrafn,Hugo,Hákon,Håkan,Håkon,Håvard,Ib,Iikka,Iiro,Iisakki,Ilari,Ilmari,Ilmarinen,Indriði,Inge,Ingemar,Ingmar,Ingolf,Ingvar,Into,Isak,Ismo,Ivar,Jaakkima,Jaakko,Jaakoppi,Jacob,Jakob,Jalmari,Jalo,Jami,Jan,Jani,Janne,Jannick,Jannik,Jari,Jarkko,Jarl,Jarle,Jarmo,Jaska,Jens,Jeppe,Jere,Jeremias,Jerk,Jerker,Jerrik,Jesper,Joakim,Joel,Johan,Johannes,Jokum,Jon,Jonas,Jonatan,Jonathan,Joni,Joona,Joonas,Jooseppi,Jorma,Josef,Joukahainen,Jouko,Jouni,Juha,Juhana,Juhani,Juho,Juhán,Jukka,Jussi,Juuso,Jyri,Jyrki,Jóhann,Jóhannes,Jón,Jónas,Jónatan,Jöran,Jörgen,Jørg,Jørgen,Jørn,Kaapo,Kaapro,Kaarle,Kaarlo,Kai,Kaj,Kaleva,Kalevi,Kalle,Kari,Karl,Kasper,Kauko,Kay,Keld,Kennet,Kenneth,Ketil,Kettil,Kevin,Kim,Kimi,Kjeld,Kjell,Kjetil,Klas,Klaus,Klemens,Knud,Knut,Knute,Konrad,Kresten,Kris,Kristen,Krister,Kristian,Kristján,Kristoffer,Kustaa,Kusti,Kyösti,Kåre,Lari,Lars,Lasse,Lassi,Launo,Lauri,Laurits,Lauritz,Leevi,Leif,Leifur,Leiv,Lelle,Lemminkäinen,Lennart,Leo,Linus,Loke,Loki,Lorens,Love,Ludde,Ludvig,Lukas,Luukas,Lárus,Lúðvík,Mads,Magne,Magnus,Mainio,Malte,Malthe,Manu,Marcus,Maria,Marius,Mark,Markku,Marko,Markus,Martin,Martti,María,Mathias,Matias,Mats,Matteus,Matthias,Matti,Mattias,Mauno,Maunu,Mauri,Max,Maximilian,Melker,Michael,Mihkkal,Mika,Mikael,Mikkel,Mikko,Miska,Mogens,Morten,Mårten,Nels,Nestori,Niels,Niilo,Niklas,Niko,Nikolaj,Nils,Njord,Njáll,Njål,Njörðr,Noak,Nooa,Nyyrikki,Odd,Oddmund,Oden,Odin,Oiva,Ola,Olaf,Olav,Olavi,Ole,Oliver,Olle,Olli,Olof,Olov,Oluf,Onni,Orla,Orvar,Oscar,Oskar,Oskari,Osku,Osvald,Otso,Otto,Ove,Paavali,Paavo,Palle,Pasi,Patrik,Paul,Pauli,Peder,Peer,Pehr,Pekka,Pekko,Pelle,Pentti,Per,Pertti,Perttu,Peter,Petri,Petter,Petteri,Philip,Pierre,Pietari,Pontus,Poul,Preben,Pyry,Páll,Pål,Pétur,Ragnar,Ragnvald,Raimo,Ralf,Ralph,Ransu,Rasmus,Reidar,Reijo,Reima,Reino,Reko,Rikard,Rikhard,Riku,Risto,Roald,Roar,Robert,Robin,Roffe,Roger,Roland,Rolf,Roni,Roope,Roopertti,Ruben,Rudolf,Rune,Ruuben,Róbert,Sakari,Sakke,Saku,Salomon,Sami,Sampo,Samppa,Samu,Samuel,Samuli,Sander,Santeri,Santtu,Sauli,Sebastian,Sepi,Seppo,Severi,Severin,Sigfrid,Sigge,Sigmund,Sigurd,Sigurðr,Sigurður,Sigvard,Simen,Simo,Simon,Sindre,Sindri,Sisu,Sixten,Sjurd,Snorre,Snorri,Soini,Staffan,Steen,Stefan,Steffen,Stefán,Stein,Steinar,Stellan,Sten,Stian,Stig,Sture,Sulo,Svante,Svein,Sven,Svend,Sverre,Sverrir,Sören,Søren,Taavetti,Taavi,Tahvo,Taisto,Tallak,Taneli,Tapani,Tapio,Tarben,Tarmo,Tatu,Tauno,Teemu,Teodor,Teppo,Terho,Terje,Tero,Teuvo,Theodor,Thomas,Thor,Thorben,Thorbjörn,Thorbjørn,Thore,Thorstein,Thorsten,Thorvald,Tiitus,Tim,Timo,Tobias,Toivo,Tollak,Tomas,Tomi,Tommi,Toni,Topi,Topias,Tor,Torben,Torbjörn,Torbjørn,Tore,Torgeir,Torger,Torgils,Torgny,Torkel,Torleif,Tormod,Torstein,Torsten,Torsti,Torvald,Troels,Trond,Truls,Tryggve,Tryggvi,Trygve,Tue,Tuomas,Tuomo,Ture,Tuukka,Tuure,Tyge,Tyko,Tyr,Tómas,Týr,Uffe,Ukko,Ulf,Ulrik,Uolevi,Urban,Urho,Usko,Valdemar,Valentin,Valter,Valto,Valtteri,Vanja,Varg,Veeti,Veikko,Veli,Verner,Vertti,Vesa,Victor,Vidar,Vieno,Viggo,Viking,Viktor,Vilfred,Vilhelm,Vilhelmi,Vilhjálmur,Vilho,Vili,Viljami,Viljo,Ville,Vilmar,Vilppu,Vincent,Vivian,Voitto,Väinämöinen,Väinö,Víðarr,Völund,Völundr,Waldemar,Walter,Werner,Yngvar,Yngve,Yngvi,Yrjänä,Yrjö,Áki,Ándaras,Árni,Ásbjörn,Ásgeir,Ásmundur,Åge,Åke,Åsmund,Ólafur,Óskar,Óðinn,Örjan,Øivind,Ørjan,Øystein,Øyvind,Þór,Þórir,Þórr,Ǫrvar";
		String hansaf = "Abigail,Ada,Adele,Adelheid,Adelina,Agathe,Agnes,Alberta,Albertina,Albina,Albine,Aleida,Aleit,Alena,Alex,Alexandra,Alexandrine,Alexia,Alexis,Alfreda,Alida,Alina,Aloisia,Amalia,Amalie,Amanda,Amelia,Amelie,Andrea,Anelie,Angela,Angelika,Angelina,Anika,Anina,Anja,Anke,Anna,Annalena,Anne,Annegret,Annelie,Annelies,Anneliese,Annemarie,Annett,Annette,Annika,Anselma,Antje,Antonia,Ariane,Astrid,Augusta,Auguste,Augustine,Aurora,Ava,Barbara,Beata,Beate,Beatrix,Benedikta,Berta,Bertha,Bettina,Bianka,Brigitta,Brigitte,Brunhild,Brunhilde,Brünhild,Bärbel,Caecilia,Carina,Carla,Carola,Carolin,Caroline,Cassandra,Cathrin,Catrin,Cecilia,Charlotte,Christa,Christel,Christiane,Christin,Christina,Christine,Clara,Claudia,Constanze,Cora,Cordula,Corina,Corinna,Cornelia,Crescentia,Cäcilia,Cäcilie,Dagmar,Dana,Daniela,Debora,Diana,Dietlinde,Doris,Dorothea,Dörthe,Ebba,Edith,Elena,Eleonora,Eleonore,Elfriede,Elisa,Elisabeth,Elise,Elke,Elli,Elma,Elsa,Else,Emilie,Emma,Erika,Ermentrud,Erna,Ernestine,Eva,Evelin,Evelyn,Felicie,Felicitas,Felizitas,Ferdinanda,Flora,Floretta,Franka,Franzi,Franziska,Frauke,Freja,Frieda,Friede,Friederike,Fritzi,Fränze,Gabi,Gabriela,Gabriele,Georgina,Gerda,Gerhild,Gerlinde,Gertraud,Gertrud,Gisa,Gisela,Gitta,Gloria,Gratia,Greta,Gretchen,Grete,Gretel,Grimhilt,Gudrun,Gunda,Gundula,Hanna,Hannah,Hanne,Hannelore,Hedwig,Hedy,Heida,Heidi,Heike,Heilwig,Heinrike,Helena,Helene,Helga,Hella,Helma,Helmine,Henriette,Henrike,Hermine,Herta,Hertha,Hilda,Hilde,Hildegard,Hildegarde,Hiltraud,Hiltrud,Hiltrude,Hulda,Ida,Ilona,Ilsa,Ilse,Imke,Imma,Ina,Inga,Inge,Ingeborg,Ingeburg,Ingrid,Inka,Irene,Iris,Irma,Irmentrud,Irmgard,Irmhild,Irmingard,Irmtraud,Irmtrud,Isa,Isabel,Isabell,Isabella,Isabelle,Isolde,Ivonne,Jana,Janina,Jasmin,Jennifer,Jenny,Jessica,Jessika,Jo,Johanna,Josefine,Josepha,Josephine,Judith,Julia,Juliana,Juliane,Justine,Jutta,Jutte,Jördis,Karen,Karin,Karina,Karla,Karola,Karolina,Karoline,Kasimira,Katarina,Katarine,Katharina,Katharine,Katherina,Kathrin,Katinka,Katja,Katrin,Katrina,Kerstin,Kiki,Kinge,Klara,Konstanze,Kora,Kornelia,Kreszentia,Kreszenz,Kriemhild,Kriemhilde,Krimhilde,Krista,Kristiane,Kristin,Kristina,Kristine,Kunigunde,Käthe,Lara,Laura,Lea,Lena,Lene,Leni,Leona,Leonie,Leonore,Liane,Lies,Liesa,Liese,Liesel,Lieselotte,Liesl,Lili,Lilli,Lilo,Linda,Lisa,Lisbeth,Liselotte,Lore,Lorelei,Lotte,Louisa,Lucia,Luise,Luitgard,Lulu,Lutgard,Luzia,Lydia,Magda,Magdalena,Magdalene,Maike,Maja,Manu,Manuela,Marcella,Mareike,Margareta,Margarete,Margaretha,Margarethe,Margrit,Maria,Marianne,Marie,Mariele,Marina,Marita,Marlen,Marlene,Marlies,Marlis,Marta,Martha,Martina,Marzanna,Mathilde,Maximiliane,Mechthild,Mechtilde,Meike,Melanie,Melitta,Meta,Mia,Michaela,Michi,Minna,Miriam,Mirjam,Mitzi,Mokosh,Monika,Morana,Nadine,Nadja,Natalie,Nathalie,Nele,Nerthus,Nicola,Nicole,Nikola,Nina,Noemi,Nora,Oda,Odilie,Olga,Olivia,Ortrun,Ottilie,Patricia,Paula,Pauline,Petra,Petronella,Philippa,Philippina,Philomena,Phyllis,Pia,Priska,Rachel,Raffaela,Raimunde,Raphaela,Rebekka,Regina,Regine,Regula,Reinhild,Reinhilde,Renata,Renate,Ria,Ricarda,Rike,Rita,Romy,Rosa,Rosalie,Rosemarie,Roswitha,Ruth,Sabine,Sabrina,Salome,Sandra,Sara,Sarah,Sascha,Saskia,Schwanhild,Selma,Senta,Seraphina,Severina,Sibylla,Sibylle,Sidonia,Sieghild,Sieglinde,Sigi,Silke,Silvia,Sofia,Sofie,Sonja,Sonje,Sophia,Sophie,Stefanie,Steffi,Steffie,Stephanie,Susann,Susanne,Suse,Susi,Svenja,Swanhild,Swanhilda,Swanhilde,Sybille,Sylvia,Tabea,Tanja,Tatiana,Tatjana,Teresa,Thea,Theda,Thekla,Theresa,Therese,Theresia,Thora,Trudi,Ulla,Ulli,Ulrike,Ursel,Ursula,Uschi,Ute,Valeria,Valerie,Valeska,Vanessa,Vera,Verena,Veronika,Victoria,Viktoria,Vilma,Vreni,Walburga,Waltraud,Wanda,Wibke,Wiebke,Wilhelmina,Wilhelmine,Willy,Wilma,Yvonne,Zella,Zenzi,Zilla,Ziska,Zita,Šiwa,Živa";
		String hansam = "Abraham,Achim,Adalbert,Adam,Adelbert,Adolf,Adrian,Alban,Alberic,Alberich,Albert,Albrecht,Alex,Alexander,Alexis,Alfons,Alfred,Alois,Aloysius,Alwin,Amand,Andreas,Anselm,Ansgar,Anton,Arend,Armin,Arndt,Arne,Arnfried,Arnold,Arthur,Artur,August,Aurel,Axel,Baldur,Baptist,Barnabas,Bartholomäus,Bastian,Beat,Ben,Benedikt,Benjamin,Benno,Bernd,Bernhard,Bert,Berthold,Bertram,Björn,Bonifaz,Boris,Bruno,Burchard,Burkhard,Burkhart,Byelobog,Carl,Carsten,Chernobog,Christian,Christoph,Claus,Clemens,Conrad,Corbinian,Cord,Cornelius,Dan,Daniel,David,Dazbog,Dazhdbog,Denis,Dennis,Detlef,Didi,Diederich,Dierk,Dieter,Dietfried,Diethelm,Dietmar,Dietrich,Dirk,Dominik,Donar,Ebbe,Eberhard,Eckart,Eckbert,Eckehard,Eckhard,Eckhart,Edmund,Eduard,Egon,Ekkehard,Ekkehardt,Elias,Elmo,Emanuel,Emil,Emmerich,Engel,Engelbert,Erdmann,Erhard,Eric,Erich,Erik,Ernst,Erwin,Etzel,Eugen,Evelyn,Evert,Ewald,Fabian,Falk,Felix,Ferdi,Ferdinand,Fester,Fiete,Filibert,Florian,Frank,Franz,Fred,Frej,Friedemann,Friedhelm,Friedhold,Friedrich,Fritz,Gabi,Gabriel,Gebbert,Gebhard,Geert,Georg,Gerald,Gerd,Gereon,Gerfried,Gerhard,Gerhardt,Gerhold,Gernot,Gero,Gerold,Gert,Gerulf,Gervas,Gilbert,Gisbert,Gottfried,Gotthard,Gotthilf,Gotthold,Gottlieb,Gottlob,Gottschalk,Gregor,Guido,Gundahar,Gunter,Gunther,Guntram,Gustaf,Gustav,Günter,Günther,Hagen,Hanke,Hanne,Hannes,Hans,Harald,Hartmann,Hartmut,Hartwig,Hartwin,Heike,Heiko,Heiner,Heino,Heinrich,Heinz,Helfried,Helge,Helmfried,Helmut,Helmuth,Hendrik,Henning,Henrik,Herbert,Heribert,Hermann,Hermenegild,Hieronymus,Hilbert,Hildebert,Hildebrand,Hinrich,Horst,Hubert,Hubertus,Hugo,Humbert,Huppert,Ignatz,Immanuel,Ing,Inge,Ingo,Ingolf,Ingomar,Isaak,Isidor,Ivo,Jakob,Jan,Jeremias,Jo,Joachim,Jochem,Jochen,Jochim,Johan,Johann,Johannes,Jonas,Jonatan,Jonathan,Josef,Joseph,Jost,Julian,Julius,Justus,Jörg,Jürgen,Kai,Karl,Karlmann,Karsten,Kasimir,Kaspar,Kay,Kayetan,Kevin,Kilian,Klaas,Klaus,Klemens,Knut,Kolman,Koloman,Konrad,Konstantin,Korbinian,Kord,Kunibert,Kuno,Kurt,Körbl,Lambert,Lammert,Lamprecht,Lanzo,Lars,Laurenz,Leberecht,Lech,Lennart,Lenz,Leo,Leon,Leonard,Leonhard,Leopold,Linus,Lorenz,Lothar,Luca,Ludger,Ludolf,Ludwig,Luitger,Luitpold,Lukas,Lutz,Malte,Malthe,Manfred,Manfried,Manu,Manuel,Marcel,Marcell,Marcellus,Marco,Maria,Marius,Markus,Martin,Marvin,Marwin,Marzell,Mathias,Mathis,Matthias,Matthäus,Mattias,Max,Maximilian,Meinard,Meine,Meinhard,Meino,Meinrad,Menno,Merten,Michael,Michel,Michi,Moritz,Mose,Nickolaus,Nico,Nicolaus,Niklas,Niklaus,Nikolaus,Norbert,Olaf,Oliver,Oral,Ortwin,Oskar,Oswald,Othmar,Otmar,Ottmar,Otto,Ottokar,Ottomar,Pankraz,Parsifal,Pascal,Patrick,Paul,Perun,Peter,Petrus,Philipp,Poldi,Quirin,Rafael,Raffael,Raimund,Rainer,Ralf,Ralph,Raphael,Reimund,Rein,Reiner,Reinhard,Reinhold,René,Reto,Richard,Robert,Rochus,Rodolf,Roger,Roland,Rolf,Roman,Rudi,Rudolf,Ruedi,Rupert,Ruprecht,Rüdiger,Samuel,Sascha,Sebastian,Sepp,Seppel,Severin,Siegbert,Siegfried,Sieghard,Siegmund,Siegward,Sigi,Sigismund,Sigmund,Silvester,Simon,Stefan,Steffen,Stephan,Stribog,Svarog,Sven,Sören,Theodor,Theophil,Thiemo,Thilo,Thomas,Thorben,Thorsten,Tiedemann,Till,Tillo,Tilo,Tim,Timo,Timotheus,Tobias,Torben,Torsten,Traugott,Udo,Ueli,Ulli,Ulrich,Urban,Urs,Utz,Uwe,Valentin,Veit,Veles,Vester,Viktor,Vinzent,Vinzenz,Volker,Volos,Waldemar,Waldo,Walter,Walther,Weland,Wendel,Wendelin,Wenzel,Wenzeslaus,Werner,Werther,Wessel,Wetzel,Wiebe,Wieland,Wilfried,Wilhelm,Willi,Willy,Wim,Winfried,Witold,Wodan,Wolf,Wolfgang,Wolfram,Wotan,Wulf,Xaver,Yvo";
		String tavianf = "Adalet,Adile,Aliye,Arzu,Asli,Asuman,Asya,Aydan,Aygül,Aygün,Ayla,Aylin,Aynur,Aysel,Aysu,Aysun,Ayten,Ayşe,Azize,Azra,Bahar,Banu,Başak,Behiye,Belgin,Berna,Berrak,Beste,Betül,Beyza,Bihter,Burcu,Burçin,Canan,Cansu,Cemile,Ceren,Cevahir,Damla,Deniz,Derya,Didem,Dilan,Dilara,Dilay,Dilek,Dilşad,Ebru,Ece,Ecrin,Eda,Ekin,Ela,Elif,Elmas,Elvan,Emel,Emine,Enise,Esen,Eser,Esin,Esma,Esra,Eylül,Ezgi,Fadime,Fahriye,Fatma,Fatoş,Fehime,Feray,Feride,Feriha,Fevziye,Fidan,Fikriye,Filiz,Firuze,Funda,Fusun,Gamze,Gaye,Gizem,Gonca,Gözde,Gül,Gülay,Gülbahar,Gülden,Gülistan,Gülizar,Gülnaz,Gülnur,Gülten,Gülşen,Günay,Hacer,Hadiiye,Hale,Halide,Halime,Hamide,Handan,Hande,Hanife,Hatice,Havva,Hazan,Hediiye,Hülya,Hüsniye,Ilkay,Ilknur,Ipek,Irem,Irmak,Jale,Kader,Kadriye,Kelebek,Kerime,Kiraz,Kismet,Lale,Latife,Leyla,Lütfiye,Makbule,Mehtap,Mehveş,Melek,Melike,Melis,Melisa,Meltem,Merve,Meryem,Müge,Müjde,Müjgan,Mümine,Münire,Nadire,Nadiye,Naile,Naime,Naz,Nazli,Nebile,Nefiset,Nehir,Nergis,Nermin,Nesim,Nesrin,Nevra,Nezihe,Nida,Nilüfer,Nimet,Nur,Nuray,Nurgül,Nurten,Pembe,Peri,Pervin,Pinar,Rabia,Reyhan,Reşide,Rukiye,Rüşen,Sabah,Sabriye,Safiye,Samiye,Sanem,Seda,Sedef,Seher,Semiha,Serpil,Sevda,Sevgi,Sevil,Sevim,Sevinç,Sidika,Sila,Simge,Sinem,Songül,Su,Sultan,Suna,Suzan,Süheyla,Sümeyye,Süreyya,Tahire,Tuba,Tutku,Tuğba,Tülay,Ulviye,Umut,Vahide,Yasemin,Yağmur,Yeter,Yeşim,Yildiz,Yonca,Zahide,Zehra,Zekiye,Zeynep,Ziynet,Zübeyde,Çağla,Çağri,Çiğdem,Özge,Özgür,Özlem,Ülkü,Şadiye,Şahnaz,Şebnem,Şehrazad,Şehrazat,Şenay,Şerife,Şermin,Şeyma,Şirin,Şukriye,Şule";
		String tavianm = "Abdullah,Abdülhamit,Abdülkadir,Abdülkerim,Abdüllatif,Adem,Adil,Adnan,Ahmed,Ahmet,Alaattin,Ali,Alim,Alp,Altan,Arda,Arif,Arslan,Asil,Asim,Aslan,Ata,Atila,Atilla,Attila,Ayberk,Aydin,Aytaç,Azad,Azat,Aziz,Babür,Baha,Bahadir,Baki,Bakir,Bariş,Bayram,Behram,Berat,Berk,Berkant,Berker,Bilal,Bilge,Bora,Boran,Bulut,Burak,Burhan,Buğra,Bülent,Bünyamin,Cafer,Can,Cebrail,Cem,Cemal,Cemil,Cengiz,Cenk,Cevdet,Cihan,Cihangir,Coşkun,Cumhur,Cüneyt,Danyal,Demir,Derviş,Devrim,Direnç,Doruk,Duygu,Ebu bekir,Ediz,Efe,Egemen,Ejder,Ekber,Ekrem,Emin,Emir,Emirhan,Emre,Ender,Enes,Engin,Enis,Enver,Ercan,Erdem,Erdoğan,Eren,Erhan,Erkan,Erkin,Erol,Evren,Eyüp,Fahri,Faruk,Fatih,Fehim,Feridun,Ferit,Fevzi,Fikri,Firat,Fuat,Galip,Göker,Gökhan,Göksu,Gürsel,Güvenç,Hadi,Hakan,Halil,Halim,Halit,Haluk,Hamit,Hamza,Harun,Hasan,Hasip,Hayati,Haydar,Hayri,Haşim,Hikmet,Hurşit,Hüseyin,Hüsnü,Ibrahim,Idris,Ihsan,Ikbal,Ilhami,Ilhan,Ilker,Ilkin,Ilyas,Irfan,Isa,Iskender,Islam,Ismail,Ismet,Izzet,Kaan,Kadir,Kadri,Kara,Kasim,Kağan,Kemal,Kerem,Kerim,Kivanç,Koray,Kudret,Kuzey,Levent,Lütfi,Lütfü,Mahir,Mahmut,Mahzun,Mansur,Mazhar,Mecit,Mehmed,Mehmet,Melik,Mert,Mesud,Mesut,Metin,Mikail,Miraç,Mithat,Muhammed,Muhammet,Muhsin,Muhtar,Murat,Musa,Mustafa,Mücahit,Mümin,Mümtaz,Münir,Naci,Nadir,Nail,Naim,Nebil,Nedim,Nesim,Nezih,Nuh,Nur,Nurettin,Nurullah,Onur,Orhan,Osman,Ozan,Polat,Rahmi,Ramazan,Rasim,Recep,Refik,Reis,Reşit,Ridvan,Rifat,Riza,Rizvan,Rüstem,Rüşen,Sabah,Sabahattin,Sabri,Sadi,Sadik,Sait,Salih,Samed,Samet,Sami,Savaş,Selahattin,Selim,Selman,Selâhattin,Semih,Semir,Serdar,Serhan,Serhat,Serkan,Seyfettin,Seyfullah,Seyyid,Seyyit,Soner,Sultan,Süheyl,Süleyman,Tahir,Talip,Talât,Taner,Tarik,Taylan,Tayyip,Temel,Tevfik,Timur,Timuçin,Tolga,Toygar,Tugay,Tuncay,Tunç,Turgay,Tutku,Ufuk,Ulvi,Umut,Ural,Utku,Uğur,Vahit,Vedat,Volkan,Vural,Yahya,Yakup,Yalçin,Yaser,Yasin,Yavuz,Yağmur,Yaşar,Yildirim,Yilmaz,Yiğit,Yunus,Yusuf,Zafer,Zekeriya,Zeki,Ziya,Ziyaeddin,Zülfikar,Çağatay,Çelik,Çetin,Ömer,Özgür,Öztürk,Ümit,Ümran,Şadi,Şahin,Şakir,Şehzade,Şemsettin,Şerif,Şukri";
		names.put("anpilayn1_f", Arrays.asList(anpilayn1f.split(",")));
		names.put("anpilayn1_m", Arrays.asList(anpilayn1m.split(",")));
		names.put("anpilayn2", Arrays.asList(anpilayn2.split(",")));
		names.put("anpilayn3_f", Arrays.asList(anpilayn3f.split(",")));
		names.put("anpilayn3_m", Arrays.asList(anpilayn3m.split(",")));
		names.put("eolsung_f", Arrays.asList(eolsungf.split(",")));
		names.put("eolsung_m", Arrays.asList(eolsungm.split(",")));
		names.put("hansa_f", Arrays.asList(hansaf.split(",")));
		names.put("hansa_m", Arrays.asList(hansam.split(",")));
		names.put("tavian_f", Arrays.asList(tavianf.split(",")));
		names.put("tavian_m", Arrays.asList(tavianm.split(",")));
}
}
